<?php
$title = 'Add new order clothes';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('orderclothes', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('order_id'));
?>
    <?= $this->render('fields.phtml') ?>
<?php

echo $this->form()->closeTag();