<?php
?>
    <h1>Добавить новое изделие</h1>
<?php
$form->setAttribute('action', $this->url('orderclothes', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('order_id'));
?>
    <?= $this->render('fields.phtml') ?>
<?php

echo $this->form()->closeTag();