<table class="myTable">

    <tr>
        <td>
            <?php $element = $cform->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('preferred_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formDate($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('textile_class'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('actual_amount'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('paytype_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('style_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('first_monogram_location'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('first_monogram_font'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('first_monogram_font_color'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('first_monogram_caption'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('second_monogram_location'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('second_monogram_font'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('second_monogram_font_color'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('second_monogram_caption'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td></td>
        <td>
            <?php echo $this->formSubmit($cform->get('orderclothescancel')); ?>
            <?php echo $this->formSubmit($cform->get('orderclothessubmit')); ?>
        </td>
        <td></td>
    </tr>

</table>



<script>
    function resetMonograms(){
        switch ($('select[name=product_id]').val()){
            case '1': showMonograms();  break;
            case '2': hideMonograms(); break;
            case '3': showMonograms(); break;
            case '4': hideMonograms(); break;
            case '5': showMonograms(); break;
        }
    }

    function showMonograms(){
        $('input[name=first_monogram_location]').parent().parent().show();
        $('input[name=first_monogram_font]').parent().parent().show();
        $('input[name=first_monogram_font_color]').parent().parent().show();
        $('input[name=first_monogram_caption]').parent().parent().show();
        $('input[name=second_monogram_location]').parent().parent().show();
        $('input[name=second_monogram_font]').parent().parent().show();
        $('input[name=second_monogram_font_color]').parent().parent().show();
        $('input[name=second_monogram_caption]').parent().parent().show();
    }

    function hideMonograms(){
        $('input[name=first_monogram_location]').parent().parent().hide();
        $('input[name=first_monogram_font]').parent().parent().hide();
        $('input[name=first_monogram_font_color]').parent().parent().hide();
        $('input[name=first_monogram_caption]').parent().parent().hide();
        $('input[name=second_monogram_location]').parent().parent().hide();
        $('input[name=second_monogram_font]').parent().parent().hide();
        $('input[name=second_monogram_font_color]').parent().parent().hide();
        $('input[name=second_monogram_caption]').parent().parent().hide();
    }

    function changeCycleDate(){
        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());
    }

    function changeTextile(){
        $('select[name=textile_class]').val($('select[name=textile_id]').val());
    }
</script>
