<?php
    $cform->setAttribute('id', 'addClothForm');
?>

<input style="display: none;" name="actual_amount" value=""/>

<table class="myTable">

    <tr>
        <td>
            <?php $element = $cform->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('preferred_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formDate($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span id="fabric_error" class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('discount_amount'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
        <td><span id="discount_error" class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr>
        <td>
            <?php $element = $cform->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr id="payment_details" style="display: none;">
        <td>
            <?php $element = $cform->get('paytype_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>
        <td><span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span></td>
    </tr>

    <tr id="payment_btn">
        <td><a style="cursor: pointer;" onclick="showPayment()"><b><i>Описать подробности оплаты <br>(только для 1-го изделия)</i></b></a></td>
        <td></td>
        <td></td>
    </tr>


    <select style="display: none;" name="style_id" value="0"> </select>

    <select id="testsuka" style="display: none;" name="label_brand" value="2">
        <option value="2">1</option>
    </select>

    <span style="font-style: italic; margin-bottom: 10px;">
        В пункте <b>подробности оплаты</b> заполняется вся информация о заказе, и пишется только на первое изделие.
    </span><br>
    <span style="font-style: italic; margin-bottom: 10px;">
        В пункте <b>номер ткани</b> если быстрая доставка, то префикс - "БД" (пример: БДDBN807A).
    </span><br>
    <span style="font-style: italic; margin-bottom: 10px;">
        В пункте <b>номер ткани</b> если супер экпресс доставка, то префикс - "СЭ" (пример: СЭDBN807A).
    </span><br>
    <a target="_blank" href="<?= $url?>"><i>Список доступных ткани</i></a>
    <br><br>

    <tr>
        <td></td>
        <td>
            <?php echo $this->formSubmit($cform->get('orderclothescancel')); ?>
            <?php echo $this->formSubmit($cform->get('orderclothessubmit')); ?>
        </td>
        <td></td>
    </tr>

</table>

<script>


    function changeCycleDate(){
        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());
    }

    function resetStylesSelect(){
        $.ajax({
            url: '/order/resetstylestoselect',
            type: 'POST',
            dataType: 'json',
            async: true,
            data: { cloth_type_id : $('select[name=product_id]').val() },
            success: function (data) {
                if(data.styles!='empty'){

                    $('select[name=style_id] option').remove();
                    $('select[name=style_id]').append($("<option></option>").attr("value",'0').text('Выберите номер стиля'));

                    for(i=0; i<data.styles.length; i++){
                        $('select[name=style_id]').append($("<option></option>").attr("value",data.styles[i]).text(data.styles[i]));
                    }
                } else {
                    $('select[name=style_id] option').remove();
                    $('select[name=style_id]').append($("<option></option>").attr("value",'0').text('Выберите номер стиля'));
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }

    $(function() {

        $('input[name=discount_amount]').val(0);

        $('select[name=product_id]').change(function() {
            fabricAjax();
        });

        $(window).keydown(function(event){
            if(event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });

        $('select[name=cycle_id]').val('');
        $($('select[name=style_id] option')[0]).val('0');
        $($('select[name=product_id] option')[0]).val('0');
        $('input[name=textile_id]').val('');

        $('#orderclothessubmit').prop('disabled',true);

        $('textarea[name=paytype_id]').css('height', '100px');
        $('textarea[name=paytype_id]').css('width', '300px');

        $('textarea[name=paytype_id]').val('нет');
    });

    $('input[name=textile_id]').focusout(function() {
        fabricAjax();
        if($('input[name=discount_amount]').val()!='' && $('select[name=product_id]').val()!=0)
            discountAjax();
    });

    $('input[name=discount_amount]').focusout(function() {
        if($('input[name=textile_id]').val()!='' && $('select[name=product_id]').val()!=0)
            discountAjax();
    });

    var discountFlag = false;
    var fabricFlag   = false;

    function discountAjax(){
        $.ajax({
            url: '/order/discountajax',
            type: 'POST',
            dataType: 'json',
            async: true,
            data: {
                    fabric: $('input[name=textile_id]').val(),
                    cloth_type: $('select[name=product_id]').val(),
                    discount: $('input[name=discount_amount]').val()
            },
            success: function (data) {

                if(data.message=='false'){
                    $('#discount_error').text('Для данной ткани скидка превышает норму');
                    discountFlag = false;
                } else{
                    $('#discount_error').text('');
                    discountFlag = true;
                }
                checkFlags();
            },
            error: function (data) {
                console.log(data);
            }
        });

        checkFlags();
    }

    function fabricAjax(){

        if($('select[name=cycle_id]').val()==-14 && $('input[name=textile_id]').val().indexOf('БД')==-1){
            $('#fabric_error').text('При цикле "-14" ткань должна начинаться с "БД"');
            fabricFlag = false;
        } else if($('select[name=cycle_id]').val()==-10 && $('input[name=textile_id]').val().indexOf('СЭ')==-1){
            $('#fabric_error').text('При цикле "-10" ткань должна начинаться с "СЭ"');
            fabricFlag = false;
        } else {
            $('#fabric_error').text('');
            $.ajax({
                url: '/order/fabricajax',
                type: 'POST',
                dataType: 'json',
                async: true,
                data: {fabric_id: $('input[name=textile_id]').val(), cloth_type: $('select[name=product_id]').val()},
                success: function (data) {
                    if(data.message=='false'){
                        $('#fabric_error').text('Такой ткани не существует');
                        fabricFlag = false;
                    } else{
                        $('#fabric_error').text('Цена: '+data.message+' тенге');
                        fabricFlag = true;

                    }
                    checkFlags();
                },
                error: function (data) {
                    console.log(data);
                }
            });
        }
        checkFlags();
    }

    function checkFlags(){
        if(discountFlag && fabricFlag){
            $('#orderclothessubmit').prop('disabled',false);
        } else{
            $('#orderclothessubmit').prop('disabled',true);
        }
    }

    function showPayment(){
        $('#payment_details').show();
        $('#payment_btn').hide();
        $('textarea[name=paytype_id]').css('width', '400px');
        $('textarea[name=paytype_id]').css('height', '150px');
        $('textarea[name=paytype_id]').val('1 часть суммы: сумма - тенге \n' +
            '1 часть суммы: способ оплаты - \n' +
            '2 часть суммы: сумма - тенге \n' +
            '2 часть суммы: способ оплаты - \n'
        );
    }

</script>
