<?php
$title = 'My customers';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('customer', array('action' => 'add')); ?>">Add new customer</a>
</p>

<!--<table class="table">
    <tr>
        <th>id</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>Дата рождения</th>
        <th>Мобильный телефон</th>
        <th>Емайл</th>
        <th>Страна</th>
        <th>Город</th>
        <th>Адресс проживания</th>
        <th>Домашний телефон</th>
        <th>Место работы</th>
        <th>Должность</th>
        <th>Адрес работы</th>
        <th>Рабочий телефон</th>
        <th>&nbsp;</th>
    </tr>
    <?php /*foreach ($customers as $customer) : */?>
        <tr>
            <td><?php /*echo $this->escapeHtml($customer->id); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->firstname); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->lastname); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->middlename); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->birthday); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->mobilephone); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->email); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->country); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->city); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->address); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->homephone); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->work); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->position); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->workaddress); */?></td>
            <td><?php /*echo $this->escapeHtml($customer->workphone); */?></td>
            <td>
                <a href="<?php /*echo $this->url('customer',
                    array('action' => 'edit', 'id' => $customer->id)); */?>">Edit</a>
                <a href="<?php /*echo $this->url('customer',
                    array('action' => 'delete', 'id' => $customer->id)); */?>">Delete</a>
            </td>
        </tr>
    <?php /*endforeach; */?>
</table>
-->

<div class="col-md-9">
    <table id="customer-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <!--<th data-column-id="id" data-type="numeric">ID</th>-->
            <th data-column-id="firstname">firstname</th>
            <th data-column-id="lastname" data-order="desc">lastname</th>
            <th data-column-id="middlename" data-order="desc">middlename</th>
            <!--<th data-column-id="birthday" data-order="desc">birthday</th>-->
            <th data-column-id="mobilephone" data-order="desc">mobilephone</th>
            <th data-column-id="email" data-order="desc">email</th>
            <th data-column-id="country" data-order="desc">country</th>
            <th data-column-id="city" data-order="desc">city</th>
            <th data-column-id="address" data-order="desc">address</th>
            <!--<th data-column-id="homephone" data-order="desc">homephone</th>
            <th data-column-id="work" data-order="desc">work</th>
            <th data-column-id="position" data-order="desc">position</th>
            <th data-column-id="workaddress" data-order="desc">workaddress</th>
            <th data-column-id="workphone" data-order="desc">workphone</th>-->
            <th data-column-id="link" data-formatter="link" data-sortable="false">Link</th>
        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script>
    $(function () {
        function init() {
            $("#customer-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        bdmode: -1
                    };
                },
                url: "/restcustomer",
                formatters: {
                    "link": function (column, row) {
                        return "<a href=\"customer/edit/"+row.id+"\">" + column.id + "</a>";


                    }
                }
            });
        }

        init();
    })

</script>