<?php
$title = '';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('order', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('customer_id'));
?>
    <div class="header">
        Заказ
    </div>

    <a class="navBtn">1 Шаг - Данные клиента</a>
    <a class="navBtn">2 Шаг - Замеры клиента</a>
    <a class="navBtn active">3 Шаг - Заказ клиента</a>

    <center>
        <div id="chooseContent">
            <?php
            ?>
        </div>
    </center>




    <div class="form-group">
        <?php $element = $form->get('dateofsale'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formDate($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>

    <div class="form-group">
        <?php $element = $form->get('pricelistnum'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>


    <div class="form-group">
        <?php $element = $form->get('payamount'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>


    <div class="form-group">
        <?php $element = $form->get('paytype'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>


    <div class="form-group">
        <?php $element = $form->get('cashlocation'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>

    <div class="form-group">
        <?php $element = $form->get('cityofsale'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>

    <div class="form-group">
        <?php $element = $form->get('pointofsale'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>

    <div class="form-group">
        <?php $element = $form->get('seller'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
<?php

echo $this->form()->closeTag();