<?php
$title = 'Edit order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'order',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

    <?= $this->render('fields.phtml') ?>

<?php

echo $this->form()->closeTag();
?>
