<?php
$title = 'Edit order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'order',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php $element = $form->get('dateofsale'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formDate($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <?php $element = $form->get('pricelistnum'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>


<div class="form-group">
    <?php $element = $form->get('payamount'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>


<div class="form-group">
    <?php $element = $form->get('paytype'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>


<div class="form-group">
    <?php $element = $form->get('cashlocation'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <?php $element = $form->get('cityofsale'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <?php $element = $form->get('pointofsale'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <?php $element = $form->get('seller'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php

echo $this->form()->closeTag();
?>


<div class="col-md-9">
    <table id="orderclothes-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="id" data-type="numeric">ID</th>
            <th data-column-id="order_id" data-order="desc">order_id</th>
            <th data-column-id="cycle_number" data-order="desc">cycle_number</th>
            <th data-column-id="product_name" data-order="desc">product_name</th>
            <th data-column-id="textile_class" data-order="desc">textile_class</th>
            <th data-column-id="textile_number" data-order="desc">textile_number</th>
            <th data-column-id="typeof_measure" data-order="desc">typeof_measure</th>
            <th data-column-id="label_brand" data-order="desc">label_brand</th>
            <th data-column-id="style_number" data-order="desc">style_number</th>
            <th data-column-id="first_monogram_location" data-order="desc">first_monogram_location</th>
            <th data-column-id="first_monogram_font" data-order="desc">first_monogram_font</th>
            <th data-column-id="first_monogram_font_color" data-order="desc">first_monogram_font_color</th>
            <th data-column-id="first_monogram_caption" data-order="desc">first_monogram_caption</th>
            <th data-column-id="second_monogram_location" data-order="desc">second_monogram_location</th>
            <th data-column-id="second_monogram_font" data-order="desc">second_monogram_font</th>
            <th data-column-id="second_monogram_font_color" data-order="desc">second_monogram_font_color</th>
            <th data-column-id="second_monogram_caption" data-order="desc">second_monogram_caption</th>
            <th data-column-id="seller_comment" data-order="desc">seller_comment</th>
            <th data-column-id="link" data-formatter="link" data-sortable="false">Link</th>
        </tr>
        </thead>
    </table>
</div>

<script>
    $(function () {
        function init() {
            $("#orderclothes-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restorderclothes",
                formatters: {
                    "link": function (column, row) {
                        return "<a href=\"orderclothes/edit/" + row.id + "\">" + column.id + "</a>";


                    }
                },
                templates: {
                    header: "<div id=\"{{ctx.id}}\" class=\"{{css.header}}\"><div class=\"row\"><div class=\"col-sm-12 actionBar\"><input type='button' value='Add'/><p class=\"{{css.search}}\"></p><p class=\"{{css.actions}}\"></p></div></div></div>"
                }
            });
        }

        init();
    })

</script>