<?php
$title = 'My orders';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="dateofsale">Дата продажи</th>
            <th data-column-id="cityofsale" data-order="desc">Город</th>
            <th data-column-id="pointofsale" data-order="desc">Место продажи</th>
            <th data-column-id="name" data-order="desc">Продовец</th>
            <th data-column-id="status" data-order="desc">Статус</th>
        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script>
    $(function () {
        function init() {
            $("#order-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restorder"
            });
        }

        init();
    })

</script>