<table id="orderclothes-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
       data-keep-selection="true">
    <thead>
    <tr>
<!--        <th data-column-id="id" data-type="numeric">ID</th>-->
<!--        <th data-column-id="order_id" data-order="desc">Номер заказа</th>-->
        <th data-column-id="cycle_id" data-order="desc">Номер цикла</th>
        <th data-column-id="clother">Тип изделия</th>
<!--        <th data-column-id="fabric_class" data-order="desc">Класс ткани</th>-->
        <th data-column-id="textile_id">Номер ткани</th>
        <!--<th data-column-id="typeof_measure" data-order="desc">typeof_measure</th>
        <th data-column-id="label_brand" data-order="desc">label_brand</th>
        <th data-column-id="style_id" data-order="desc">style_id</th>
-->
        <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

    </tr>
    </thead>
</table>


<script>
    $(function () {

//        alert(<?//=$customer->id?>//);
//        alert(<?//= $order_form_id ?>//);

        function init() {
            var grid = $("#orderclothes-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: <?= $order_form_id ?>,
                        order_status: 14
                    };
                },
                url: "/restorderclothes",
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.my_id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".command-delete").on("click", function(e)
                {
                    myId=$(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы действительно хотите удалить выбранную запись?", function(result) {
                        if(result){
                            $.post( "../../deletecloth/"+myId, { id: myId } ).done(function( data ) {
                                $('#orderclothes-grid').bootgrid('reload');
                            });
                        }
                    });
                });
            });
        }
        init();
    })

</script>