<?php
$title = '';
$this->headTitle($title);
?>
<h1 xmlns="http://www.w3.org/1999/html"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('order', array('action' => 'thirdstep', 'id' => $this->id,)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();


$order_form_id_elem = new \Zend\Form\Element\Hidden('order_form_id');
$order_form_id_elem->setValue($order_form_id);

echo $this->form()->openTag($form);
echo $this->formHidden($order_form_id_elem);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('customer_id'));
echo $this->formHidden($form->get('status'));

?>
<div style="text-align:center;">
    <div class="header">
        Заказ
    </div>

    <a class="navBtn">1 Шаг - Данные клиента</a>
    <a class="navBtn">2 Шаг - Замеры клиента</a>
    <a class="navBtn active">3 Шаг - Заказ клиента</a>


    <div id="chosenClient">
        <?php
        echo 'Выбранный клиент: '.$customer->lastname." ".$customer->firstname.", ".$customer->mobilephone;
        ?>
    </div>
</div>


<?= $this->render('fields.phtml') ?>

<span class="help-block" style="color:red"><?php echo $order_error ?></span>

<?php
if ($orderclothesform) { ?>
    <div class="col-md-9">

        <?php
        ?>
        <h1>Добавить новое изделие</h1>
        <?php
        echo $this->formHidden($cform->get('c_id'));
        echo $this->formHidden($cform->get('order_id'));
        ?>

        <?= $this->render('/pidzhak/order-clothes/fields_cform.phtml') ?>

    </div>
<?php } ?>


<?php
if (!$orderclothesform) { ?>
    <div class="col-md-9">
        <input type='submit' name='addclothessubmit' id='addclothessubmit' class='btn btn-default addClothes'
               value='Добавить изделия'/>
        <?= $this->render('third_list_clothes.phtml') ?>
    </div>
<?php } ?>


<?php
echo $this->form()->closeTag();
?>


<?php
if (!$orderclothesform) { ?>
    <div class="col-md-9">
        <?php echo $this->form()->openTag($form);
        echo $this->formHidden($order_form_id_elem); ?>
        <input type='submit' name='sendordersubmit' id='sendordersubmit' class='btn btn-primary'   value='Отправить заказ'/>
        <?php echo $this->form()->closeTag(); ?>
    </div>
<?php } ?>




