<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 17/06/2015
 * Time: 19:47
 */
?>

<div class="header">
Финансовые операции
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


<a class="btn btn-primary" href="accountant/add">Добавить новую операцию</a>


<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="id" data-order="desc">Номер</th>
            <th data-type="datetime" data-column-id="oper_date">Дата операции</th>
            <th data-column-id="oper_type">Тип операции</th>
            <th data-column-id="oper_cost">Сумма операции</th>
            <th data-type="oper_cost" data-column-id="cashbox">Итого в кассе</th>
<!--            <th data-column-id="oper_comment">Комментарии</th>-->
            <th data-column-id="oper_status">Статус</th>

            <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>


<div id="myModal" style="display: none; text-align: center">

    <input style="display: none" id="order_cloth_id" />
    <input style="display: none;" id="oldComment" />
    <input style="display: none;" id="tailorName" />

    <table style="width: 100%; text-align: left;">
        <tr>
            <td>Отзыв:</td>
            <td><textarea required="true" id="comment" class="form-control" style="width: 350px;"></textarea></td>
        </tr>
    </table>

    <button onclick="closeDlg()" class="btn btn-default" style="margin-top: 8px; margin-right:10px;">Отмена</button>
    <button onclick="setArrived();" class="btn btn-primary" style="margin-top: 8px;">Отправить</button>

</div>

<div id="tracking" style="display: none;">
</div>

<script>
$(function () {

    hideMenu();

    $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd'});

        function init() {
            var grid = $("#order-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                /* To accumulate custom parameter with the request object */
                return {
                    id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restfinance",
                converters: {
                datetime: {
                    from: function (value) { return value; },
                    to: function (value) {
                        temp = value.split('-');
                        return temp[2]+'/'+temp[1]+'/'+temp[0];
                        }
                }
            },
                formatters: {
                "commands": function(column, row)
                    {
                        return  "<button data-row-comment='"+row.oper_comment+"' type=\"button\" class=\"btn btn-xs btn-primary showComment\">Подробности</button>"+
                                "<button style='margin-left: 3px; margin-right: 3px;' type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>"+
                                "<button type=\"button\" class=\"btn btn-xs btn-default confirm\" data-row-id=\"" + row.id + "\"><span class=\"glyphicon glyphicon-ok\"></span></button>";
//
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".enterCodes").on("click", function(e)
                {
//                    var url="http://localhost:8080/seller/watchold/"+$(this).data("row-id")
                    var url="http://adminpidzhak.kz/seller/watchold/"+$(this).data("row-id")
                    window.open(url, 'Старые замеры', "height=800,width=800");
//                    openDlg($(this).data("row-id"), $(this).data("row-comment"), $(this).data("row-tailor"));
                }).end().find(".showComment").on("click", function(e)
                {
                    showCommentDlg($(this).data("row-comment"));
                }).end().find(".command-delete").on("click", function(e)
                {
                    myId=$(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы действительно хотите удалить выбранную запись?", function(result) {
                        if(result){
                            $.post( "accountant/delete/"+myId, { id: myId } ).done(function( data ) {
                                $('#order-grid').bootgrid('reload');
                            });
                        };
                    });
                }).end().find(".confirm").on("click", function(e)
                    {
                        myId=$(this).data("row-id");
                        bootbox.setDefaults({
                            locale: "ru",
                            className: "my-modal"
                        });
                        bootbox.confirm("Вы действительно подтвердить данную операцию?", function(result) {
                            if(result){
                                $.post( "accountant/confirm/"+myId, { id: myId } ).done(function( data ) {
                                    $('#order-grid').bootgrid('reload');
                                });
                            };
                        });
                });
            });
        }
        init();


        $('.right-section').css('width', '100%');
    });

    function openDlg(id, comment, tailorId){

        $('#order_cloth_id').val(id);
        $('#comment').css('width','500px');
        $('#oldComment').val(comment);

        switch (tailorId){
            case 1: $('#tailorName').val('Ирина'); break;
            case 2: $('#tailorName').val('Майя'); break;
        }

        $('#myModal').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 600,
            height: 200,
            title: 'Оставить отзыв клиента'
        });
    }

    function closeDlg(){
        $('#myModal').dialog('close');
    }

    function setArrived(){
        if($('#order_cloth_id').val()!='')
            $.post( "feedback", { id: $('#order_cloth_id').val(), comment: $('#oldComment').val() +'<br>' +'Отзыв оставлен '+getToday()+': '+ $('#comment').val() } ).done(function( data ) {
            closeDlg();
            $('#order-grid').bootgrid('reload');
        });
    }

    function showCommentDlg(comment){
        $('#tracking').html(comment);

        $('#tracking').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 500,
            height: 335,
            title: 'Комментарий'
        });
    }

    function getToday(){
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth()+1; //January is 0!

        var yyyy = today.getFullYear();
        if(dd<10){
            dd='0'+dd
        }
        if(mm<10){
            mm='0'+mm
        }
        var today = dd+'/'+mm+'/'+yyyy;

        return today;
    }
</script>