<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 16/04/2015
 * Time: 18:15
 */
?>

<div class="header">
    Добавление нового пользывателя
</div>

<?php
$form->setAttribute('action', $this->url('clients', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>


    <?= $this->render('/pidzhak/customer/fields.phtml') ?>


<?php


echo $this->form()->closeTag();
?>


<script>
    $(function(){
        $("#mobilephone").mask("99999999999");
    })
</script>