<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 16/04/2015
 * Time: 18:15
 */
?>

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script src="https://apis.google.com/js/client.js"></script>
<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>-->

<div class="header">
    Добавление нового пользывателя
</div>

<?php
$form->setAttribute('action', $this->url('clients', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

    <?= $this->render('/pidzhak/customer/fields.phtml') ?>

    <input name="access_token" style="display:none" />

<?php
    echo $this->form()->closeTag();
?>


<script>
    $(function(){
        $("#mobilephone").mask("99999999999");
        setTimeout(function(){ createContact(); }, 1000);
    })
    function createContact(){
        var config = {
            'client_id': '293748932350-ttdh6gkvjb095gj5fuhhjqs32d5dnq2l.apps.googleusercontent.com',
            'scope': 'https://www.google.com/m8/feeds'
        };
        gapi.auth.authorize(config, function() {
            doSmth(gapi.auth.getToken());
        });
    }
    function doSmth(access_token){
        $('input[name=access_token]').val(access_token.access_token);
    }
</script>