<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 17/04/2015
 * Time: 10:52
 */
?>

<div class="header">
    Добавление новой ткани
</div>

<?php
$form->setAttribute('action', $this->url('fabrics', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
    <?php $element = $form->get('fabric_class'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <?php $element = $form->get('fabric_available_start_date'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formDate($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <a class="btn btn-default cancel-btn" href="/fabrics">Отменить</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>