<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 22/04/2015
 * Time: 11:21
 */
?>

<div class="header">
Добавление нового прайса
</div>

<?php
$form->setAttribute('action', $this->url('prices', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'newForm');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
    <?php $element = $form->get('fabric_class'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formSelect($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <?php $element = $form->get('cloth_type'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formSelect($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
    <div class="form-group">
        <?php $element = $form->get('price'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formNumber($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('profit'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formNumber($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('max_discount'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formNumber($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <a class="btn btn-default cancel-btn" href="/prices">Отменить</a>
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

<?php
echo $this->form()->closeTag();
?>

<button onclick="submitAjax()">AjaxSubmit</button>

<script>
    function submitAjax(){

        $.ajax({
            url: '/prices/ajaxadd',
            type: 'POST',
            dataType: 'json',
            async: true,
            data: $("#newForm").serialize(),
            success: function (data) {
                $('.error').remove();
                for (var prop in data) {
                    if (data.hasOwnProperty(prop)) {
                        $('input[name='+prop+']').after('<span class="error" style="color: red;">'+data[prop][0]+'</span>');
                    }
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
</script>