<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 12/08/2015
 * Time: 17:23
 */
?>

<div class="header">
    Список связей
</div>

<a class="btn btn-primary" href="/suppliers/create">Добавить новую связь</a>

<div class="col-md-9">
    <table id="penalty-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="supplier_name" data-order="desc">Поставщик</th>
            <th data-column-id="fabric_class">Класс ткани</th>

            <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
        </tr>
        </thead>

    </table>
</div>


<script>
    $(function () {
        function init() {
            var grid = $("#penalty-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restconnection",
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-fabric=\"" + row.fabric_class + "\" data-row-id=\"" + row.supplier_id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".command-edit").on("click", function(e)
                {
                    window.location="suppliers/edit/"+$(this).data("row-id");
                }).end().find(".command-delete").on("click", function(e)
                {
                    supp_id=$(this).data("row-id");
                    fabric_class=$(this).data("row-fabric");

                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы действительно хотите удалить выбранную запись?", function(result) {
                        if(result){
                            $.post("suppliers/deleteconn/"+supp_id, {supp_id: supp_id, fabric: fabric_class}).done(function(data) {
                                $('#penalty-grid').bootgrid('reload');
                            });
                        };
                    });
                });
            });
        }
        init();
    })

</script>