<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 12/08/2015
 * Time: 17:24
 */
?>

<div class="header">
    Создание новой связи между поставщиком и классом ткани
</div>

<?php
    $form->setAttribute('action', $this->url('suppliers', array('action' => 'create')));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();

    echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?php $element = $form->get('supplier_id'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formSelect($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <?php $element = $form->get('fabric_class'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formSelect($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>

<div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <a class="btn btn-default cancel-btn" href="/suppliers/connections">Отменить</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>