<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 17/04/2015
 * Time: 10:55
 */
?>

<div class="header">
    Редактирование стиля
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'styles',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

    <table class="myTable">

        <tr>
            <td>
                <?php $element = $form->get('style_num'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td>
                <?php echo $this->formText($element); ?>
                <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
            </td>
        </tr>

        <tr>
            <td>
                <?php $element = $form->get('cloth_type'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td>
                <?php echo $this->formSelect($element); ?>
                <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
            </td>
        </tr>

    </table>

    <hr>

    <?php
        $sc_form->setAttribute('class', 'form-horizontal');
        $sc_form->prepare();
        echo $this->form()->openTag($sc_form);
    ?>
    <div id="testModel">
        <?php
        $systemCodeForm = $sc_form->get('systemcode');
        echo $this->formCollection($systemCodeForm);
        ?>
    </div>

    <?php
        echo $this->formHidden($sc_form->get('csrf'));
    ?>
    <button type="button" class="btn btn-default" onclick="addCode()">Добавить строку</button>

    <hr>


    <a class="btn btn-default cancel-btn" href="/styles">Отменить</a>
    <?php echo $this->formSubmit($form->get('submit')); ?>

<?php
    echo $this->form()->closeTag();
?>


<script>
    $(function() {
        styleRows();
        var fieldsets = $('#testModel').find('fieldset');
        for(i=0; i<fieldsets.length; i++){
            if(i!=0 && i!=1) $(fieldsets[i]).find('span').remove();
        }
    });

    function addCode(){
        var currentCount = $('#testModel').find('fieldset').length;
        var template = $('#testModel').find('span').last().data('template');
        template = template.replace(/__mycount__/g, currentCount);

        $('#testModel').find('fieldset').last().after(template);
        $('#testModel').find('fieldset').last().find('span').remove();
        styleRows();
        return false;
    }

    function deleteRowClick(row){
        row.parent().remove();
    }

    function styleRows(){
        $('#testModel').find('fieldset').find('label').css('margin-right', '5px');
    }
</script>