<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 11/08/2015
 * Time: 12:18
 */
?>

<div class="header">
    Редактирование штрафа
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'penalties',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
    <?php $element = $form->get('penalty_name'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <?php $element = $form->get('penalty_comment'); ?>
    <?php echo $this->formLabel($element); ?>
    <div class="col-xs-10">
        <?php echo $this->formText($element); ?>
    </div>
    <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
</div>
<div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <a class="btn btn-default cancel-btn" href="/penalties">Отменить</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>