<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 10.04.2015
 * Time: 15:20
 */
?>

<div class="header">
    Управление пользывателями
</div>

<div class="col-md-9">
    <table id="user-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="name">Имя</th>
            <th data-column-id="surname" data-order="desc">Фамилия</th>
            <th data-column-id="username" data-order="desc">Логин</th>
            <th data-column-id="access_type_id" data-order="desc">Роль</th>
            <th data-column-id="email" data-order="desc">Почта</th>
            <th data-column-id="phone" data-order="desc">Телефон</th>

            <th data-column-id="link" data-formatter="link" data-sortable="false">Редактировать</th>
        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script type="text/javascript">
    $(function () {
        function init() {
            $("#user-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restadmin",
                formatters: {
                    "link": function (column, row) {
                        return "<a href=\"admin/edit/"+row.id+"\">" + column.id + "</a>";
                    }
                }
            });
        }

        init();
    })

</script>