<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 10.04.2015
 * Time: 15:20
 */
?>

<div class="header">
    Управление пользывателями
</div>

<div class="col-md-9">
    <table id="user-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="name">Имя</th>
            <th data-column-id="surname" data-order="desc">Фамилия</th>
            <th data-column-id="username" data-order="desc">Логин</th>
            <th data-column-id="role_name" data-order="desc">Роль</th>
            <th data-column-id="email" data-order="desc">Почта</th>
            <th data-column-id="phone" data-order="desc">Телефон</th>

            <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script type="text/javascript">
    $(function () {
        function init() {
            var grid =  $("#user-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restadmin",
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\" data-row-id=\"" + row.user_id + "\"><span class=\"glyphicon glyphicon-pencil\"></span></button> " +
                            "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.user_id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".command-edit").on("click", function(e)
                {
                    window.location="admin/edit/"+$(this).data("row-id");
                }).end().find(".command-delete").on("click", function(e)
                {
                    myId=$(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы действительно хотите удалить выбранную запись?", function(result) {
                        if(result){
                            $.post( "admin/delete/"+myId, { id: myId } ).done(function( data ) {
                                $('#user-grid').bootgrid('reload');
                            });
                        };
                    });
                });
            });
        }

        init();
    })

</script>