<html>
<head>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script src="https://apis.google.com/js/client.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

    <script>
        function auth() {
            var config = {
                'client_id': '953149846914-4mahib5a15dkpnor8c72d1am9sp120c7.apps.googleusercontent.com',
                'scope': 'https://www.google.com/m8/feeds'
            };
            gapi.auth.authorize(config, function() {
                fetch(gapi.auth.getToken());
            });
        }

        function fetch(token) {
            $.ajax({
                url: "https://www.google.com/m8/feeds/contacts/default/full?access_token=" + token.access_token + "&alt=json",
                dataType: "jsonp",
                success:function(data) {
                    console.log(JSON.stringify(data));
                },
                error : function (xhr, ajaxOptions, thrownError) {
                    console.log(xhr.status);
                    console.log(thrownError);
                }
            });
        }
    </script>
</head>

<body>
<button onclick="auth();">GET CONTACTS FEED</button>
</body>
</html>