<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 22/04/2015
 * Time: 11:20
 */
?>

<div class="header">
СМСы
</div>

<div class="col-md-9">
    <table id="sms-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="id">id</th>
            <th data-column-id="text" data-order="desc">text</th>
            <th data-column-id="variables" data-order="desc">variables</th>
            <th data-column-id="credits" data-order="desc">credits</th>
            <th data-column-id="sentdate" data-order="desc">sentdate</th>
            <th data-column-id="donedate" data-order="desc">donedate</th>
            <th data-column-id="first_status" data-order="desc">first_status</th>
            <th data-column-id="status" data-order="desc">status</th>
            <th data-column-id="send_sms_xml" data-order="desc">send_sms_xml</th>

            <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
        </tr>
        </thead>

    </table>
</div>

<script>
    $(function () {
        function init() {
            var grid = $("#sms-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restsms",
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-default command-status\" data-row-id=\"" + row.id + "\"><span class=\"glyphicon glyphicon-refresh\"></span></button> ";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".command-status").on("click", function(e)
                {
                    var msgId = $(this).data("row-id");
                    $.get("/restsms/"+msgId).done(function() {
                        $('#sms-grid').bootgrid('reload');
                    });
                });
            });
        }
        init();
    })

</script>