<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 13/08/2015
 * Time: 11:37
 */
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Срочные ткани в корзине
</div>

<div class="col-md-9">
    <table id="ordercloth-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="redactorNumColumns2" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл*</th>
            <th data-column-id="customer_full_name" >Клиент*</th>
            <th data-header-css-class="redactorNumColumns2" data-column-id="my_id">ID*</th>
            <th data-header-css-class="redactorNumColumns2" data-column-id="excel_order_id">HK_ID</th>
            <th data-header-css-class="redactorClothColumn" data-column-id="clother">Изделие*</th>
            <th data-column-id="fabric_class">Класс ткани</th>
            <th data-header-css-class="redactorNumColumns" data-type="numeric" data-column-id="textile_id">Ткань</th>
            <th data-type="code" data-column-id="code_status">Code status</th>
            <th data-type="fabric_status" data-column-id="fabric_status">Fabric status</th>
            <th data-column-id="seller_full_name">Помощник*</th>
        </tr>
        </thead>
    </table>
</div>

<button class="btn btn-primary" onclick="sendEmail()" style="float: right; margin-right: 15px;">Отправить емайл</button>

<div id="emailDlg" style="display: none;" title="Форма отправки емайла">
    email goes here
</div>

<script>

    $(function () {

        hideMenu();

        function init() {
            var grid = $("#ordercloth-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '',
                        order_status: 21
                    };
                },
                url: "/restorderclothes",
                converters: {
                    code: {
                        from: function (value) { return value; },
                        to: function (value) {
                            if(value==null || value==0){ return 'New';
                            } else if(value==1){ return 'Some codes';
                            } else if(value==3){ return 'Ready';
                            } else if(value==4){ return 'Returned by Seller';
                            } else if(value==5){ return 'Waiting response';
                            } else if(value==111){ return 'Аннулированный';
                            } else if(value==7){ return 'Returned by Assistant';
                            }
                        }
                    },
                    fabric_status: {
                        from: function (value) { return value; },
                        to: function (value) {
                            if(value==null || value==0){ return 'New';
                            } else if(value==2){ return 'В пути';
                            } else if(value==3){ return 'Готово';
                            } else if(value==6){ return 'В корзине';
                            }
                        }
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                //
            });
        }
        init();
    });

    function sendEmail(){
        $('#emailDlg').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 550,
            height: 350
        });
    }

</script>