<table>
    <thead>
    <tr>
        <td></td>
        <th>Пиджак</th>
        <th>Брюки</th>
        <th>Сорочка</th>
        <th>Жилетка</th>
        <th>Пальто</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->formLabel($form->get('growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('growth_2')); ?></td>
        <td><?php echo $this->formText($form->get('growth_3')); ?></td>
        <td><?php echo $this->formText($form->get('growth_4')); ?></td>
        <td><?php echo $this->formText($form->get('growth_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('weight_2')); ?></td>
        <td><?php echo $this->formText($form->get('weight_3')); ?></td>
        <td><?php echo $this->formText($form->get('weight_4')); ?></td>
        <td><?php echo $this->formText($form->get('weight_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('arm_position_1')); ?></td>
        <td><?php echo $this->formSelect($form->get('arm_position_1')); ?></td>
        <td><?php echo $this->formText($form->get('arm_position_2')); ?></td>
        <td><?php echo $this->formText($form->get('arm_position_3')); ?></td>
        <td><?php echo $this->formText($form->get('arm_position_4')); ?></td>
        <td><?php echo $this->formSelect($form->get('arm_position_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('butt_position_1')); ?></td>
        <td><?php echo $this->formText($form->get('butt_position_1')); ?></td>
        <td><?php echo $this->formSelect($form->get('butt_position_2')); ?></td>
        <td><?php echo $this->formText($form->get('butt_position_3')); ?></td>
        <td><?php echo $this->formText($form->get('butt_position_4')); ?></td>
        <td><?php echo $this->formText($form->get('butt_position_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('neck_2')); ?></td>
        <td><?php echo $this->formText($form->get('neck_3')); ?></td>
        <td><?php echo $this->formText($form->get('neck_4')); ?></td>
        <td><?php echo $this->formText($form->get('neck_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('chest_1')); ?></td>
        <td><?php echo $this->formText($form->get('chest_1')); ?></td>
        <td><?php echo $this->formText($form->get('chest_2')); ?></td>
        <td><?php echo $this->formText($form->get('chest_3')); ?></td>
        <td><?php echo $this->formText($form->get('chest_4')); ?></td>
        <td><?php echo $this->formText($form->get('chest_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('stomach_1')); ?></td>
        <td><?php echo $this->formText($form->get('stomach_1')); ?></td>
        <td><?php echo $this->formText($form->get('stomach_2')); ?></td>
        <td><?php echo $this->formText($form->get('stomach_3')); ?></td>
        <td><?php echo $this->formText($form->get('stomach_4')); ?></td>
        <td><?php echo $this->formText($form->get('stomach_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('seat_1')); ?></td>
        <td><?php echo $this->formText($form->get('seat_1')); ?></td>
        <td><?php echo $this->formText($form->get('seat_2')); ?></td>
        <td><?php echo $this->formText($form->get('seat_3')); ?></td>
        <td><?php echo $this->formText($form->get('seat_4')); ?></td>
        <td><?php echo $this->formText($form->get('seat_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('thigh_1')); ?></td>
        <td><?php echo $this->formText($form->get('thigh_1')); ?></td>
        <td><?php echo $this->formText($form->get('thigh_2')); ?></td>
        <td><?php echo $this->formText($form->get('thigh_3')); ?></td>
        <td><?php echo $this->formText($form->get('thigh_4')); ?></td>
        <td><?php echo $this->formText($form->get('thigh_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('knee_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('knee_finished_3')); ?></td>
        <td><?php echo $this->formText($form->get('knee_finished_4')); ?></td>
        <td><?php echo $this->formText($form->get('knee_finished_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('pant_bottom_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('pant_bottom_finished_3')); ?></td>
        <td><?php echo $this->formText($form->get('pant_bottom_finished_4')); ?></td>
        <td><?php echo $this->formText($form->get('pant_bottom_finished_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('u_rise_1')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_1')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_2')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_3')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_4')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('u_rise_auto_1')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_auto_1')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_auto_2')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_auto_3')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_auto_4')); ?></td>
        <td><?php echo $this->formText($form->get('u_rise_auto_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('otseam_l_and_r_1')); ?></td>
        <td><?php echo $this->formText($form->get('otseam_l_and_r_1')); ?></td>
        <td><?php echo $this->formText($form->get('otseam_l_and_r_2')); ?></td>
        <td><?php echo $this->formText($form->get('otseam_l_and_r_3')); ?></td>
        <td><?php echo $this->formText($form->get('otseam_l_and_r_4')); ?></td>
        <td><?php echo $this->formText($form->get('otseam_l_and_r_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('nape_to_waist_1')); ?></td>
        <td><?php echo $this->formText($form->get('nape_to_waist_1')); ?></td>
        <td><?php echo $this->formText($form->get('nape_to_waist_2')); ?></td>
        <td><?php echo $this->formText($form->get('nape_to_waist_3')); ?></td>
        <td><?php echo $this->formText($form->get('nape_to_waist_4')); ?></td>
        <td><?php echo $this->formText($form->get('nape_to_waist_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('front_waist_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_length_2')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_length_3')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_length_4')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_length_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('back_waist_height_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_waist_height_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_waist_height_2')); ?></td>
        <td><?php echo $this->formText($form->get('back_waist_height_3')); ?></td>
        <td><?php echo $this->formText($form->get('back_waist_height_4')); ?></td>
        <td><?php echo $this->formText($form->get('back_waist_height_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('front_waist_height_1')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_height_1')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_height_2')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_height_3')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_height_4')); ?></td>
        <td><?php echo $this->formText($form->get('front_waist_height_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('biceps_1')); ?></td>
        <td><?php echo $this->formText($form->get('biceps_1')); ?></td>
        <td><?php echo $this->formText($form->get('biceps_2')); ?></td>
        <td><?php echo $this->formText($form->get('biceps_3')); ?></td>
        <td><?php echo $this->formText($form->get('biceps_4')); ?></td>
        <td><?php echo $this->formText($form->get('biceps_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('back_shoulder_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_shoulder_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_shoulder_2')); ?></td>
        <td><?php echo $this->formText($form->get('back_shoulder_3')); ?></td>
        <td><?php echo $this->formText($form->get('back_shoulder_4')); ?></td>
        <td><?php echo $this->formText($form->get('back_shoulder_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('right_sleeve_1')); ?></td>
        <td><?php echo $this->formText($form->get('right_sleeve_1')); ?></td>
        <td><?php echo $this->formText($form->get('right_sleeve_2')); ?></td>
        <td><?php echo $this->formText($form->get('right_sleeve_3')); ?></td>
        <td><?php echo $this->formText($form->get('right_sleeve_4')); ?></td>
        <td><?php echo $this->formText($form->get('right_sleeve_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('left_sleeve_1')); ?></td>
        <td><?php echo $this->formText($form->get('left_sleeve_1')); ?></td>
        <td><?php echo $this->formText($form->get('left_sleeve_2')); ?></td>
        <td><?php echo $this->formText($form->get('left_sleeve_3')); ?></td>
        <td><?php echo $this->formText($form->get('left_sleeve_4')); ?></td>
        <td><?php echo $this->formText($form->get('left_sleeve_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('back_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('back_length_2')); ?></td>
        <td><?php echo $this->formText($form->get('back_length_3')); ?></td>
        <td><?php echo $this->formText($form->get('back_length_4')); ?></td>
        <td><?php echo $this->formText($form->get('back_length_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('overcoat_back_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('overcoat_back_length_1')); ?></td>
        <td><?php echo $this->formText($form->get('overcoat_back_length_2')); ?></td>
        <td><?php echo $this->formText($form->get('overcoat_back_length_3')); ?></td>
        <td><?php echo $this->formText($form->get('overcoat_back_length_4')); ?></td>
        <td><?php echo $this->formText($form->get('overcoat_back_length_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('waist_1')); ?></td>
        <td><?php echo $this->formText($form->get('waist_1')); ?></td>
        <td><?php echo $this->formText($form->get('waist_2')); ?></td>
        <td><?php echo $this->formText($form->get('waist_3')); ?></td>
        <td><?php echo $this->formText($form->get('waist_4')); ?></td>
        <td><?php echo $this->formText($form->get('waist_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('right_wrist_1')); ?></td>
        <td><?php echo $this->formText($form->get('right_wrist_1')); ?></td>
        <td><?php echo $this->formText($form->get('right_wrist_2')); ?></td>
        <td><?php echo $this->formText($form->get('right_wrist_3')); ?></td>
        <td><?php echo $this->formText($form->get('right_wrist_4')); ?></td>
        <td><?php echo $this->formText($form->get('right_wrist_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('left_wrist_1')); ?></td>
        <td><?php echo $this->formText($form->get('left_wrist_1')); ?></td>
        <td><?php echo $this->formText($form->get('left_wrist_2')); ?></td>
        <td><?php echo $this->formText($form->get('left_wrist_3')); ?></td>
        <td><?php echo $this->formText($form->get('left_wrist_4')); ?></td>
        <td><?php echo $this->formText($form->get('left_wrist_5')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('style_1')); ?></td>
        <td><?php echo $this->formSelect($form->get('style_1')); ?></td>
        <td><?php echo $this->formSelect($form->get('style_2')); ?></td>
        <td><?php echo $this->formSelect($form->get('style_3')); ?></td>
        <td><?php echo $this->formSelect($form->get('style_4')); ?></td>
        <td><?php echo $this->formSelect($form->get('style_5')); ?></td>
    </tr>
    </tbody>
</table>

<script>
    $(document).ready(function(){
        $('input[name=growth_1], input[name=growth_2], input[name=growth_3], input[name=growth_4], input[name=growth_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || // Allow: backspace, delete, tab, escape, enter and .
                (e.keyCode == 65 && e.ctrlKey === true) || // Allow: Ctrl+A
                (e.keyCode >= 35 && e.keyCode <= 40)) {// Allow: home, end, left, right, down, up
                return; // let it happen, don't do anything
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        $('input[name=weight_1], input[name=weight_2], input[name=weight_3], input[name=weight_4], input[name=weight_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=neck_1], input[name=neck_3], input[name=neck_4], input[name=neck_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=chest_1], input[name=chest_3], input[name=chest_4], input[name=chest_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=stomach_1], input[name=stomach_3], input[name=stomach_4], input[name=stomach_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=seat_2], input[name=thigh_2], input[name=knee_finished_2], input[name=pant_bottom_finished_2], input[name=u_rise_2], input[name=u_rise_auto_2], input[name=otseam_l_and_r_2]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=nape_to_waist_1], input[name=nape_to_waist_3], input[name=nape_to_waist_4], input[name=nape_to_waist_5], input[name=front_waist_length_1], input[name=front_waist_length_3], input[name=front_waist_length_4], input[name=front_waist_length_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=back_waist_height_2], input[name=back_waist_height_4], input[name=front_waist_height_2], input[name=front_waist_height_4], input[name=biceps_1], input[name=biceps_3], input[name=biceps_5], input[name=back_shoulder_1], input[name=back_shoulder_3], input[name=back_shoulder_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=right_sleeve_1], input[name=right_sleeve_3], input[name=right_sleeve_5], input[name=left_sleeve_1], input[name=left_sleeve_3], input[name=left_sleeve_5], input[name=back_length_1], input[name=back_length_3], input[name=back_length_5]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=overcoat_back_length_5], input[name=waist_2], input[name=right_wrist_3], input[name=left_wrist_3], input[name=butt_position_2]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=growth_1]').bind("change paste keyup", function() {
            $('input[name=growth_2]').val($(this).val()); $('input[name=growth_3]').val($(this).val()); $('input[name=growth_4]').val($(this).val()); $('input[name=growth_5]').val($(this).val());
        });
        $('input[name=growth_2]').bind("change paste keyup", function() {
            $('input[name=growth_1]').val($(this).val()); $('input[name=growth_3]').val($(this).val()); $('input[name=growth_4]').val($(this).val()); $('input[name=growth_5]').val($(this).val());
        });
        $('input[name=growth_3]').bind("change paste keyup", function() {
            $('input[name=growth_1]').val($(this).val()); $('input[name=growth_2]').val($(this).val()); $('input[name=growth_4]').val($(this).val()); $('input[name=growth_5]').val($(this).val());
        });
        $('input[name=growth_4]').bind("change paste keyup", function() {
            $('input[name=growth_1]').val($(this).val()); $('input[name=growth_2]').val($(this).val()); $('input[name=growth_3]').val($(this).val()); $('input[name=growth_5]').val($(this).val());
        });
        $('input[name=growth_5]').bind("change paste keyup", function() {
            $('input[name=growth_1]').val($(this).val()); $('input[name=growth_2]').val($(this).val()); $('input[name=growth_3]').val($(this).val()); $('input[name=growth_4]').val($(this).val());
        });

        $('input[name=weight_1]').bind("change paste keyup", function() {
            $('input[name=weight_2]').val($(this).val()); $('input[name=weight_3]').val($(this).val()); $('input[name=weight_4]').val($(this).val()); $('input[name=weight_5]').val($(this).val());
        });
        $('input[name=weight_2]').bind("change paste keyup", function() {
            $('input[name=weight_1]').val($(this).val()); $('input[name=weight_3]').val($(this).val()); $('input[name=weight_4]').val($(this).val()); $('input[name=weight_5]').val($(this).val());
        });
        $('input[name=weight_3]').bind("change paste keyup", function() {
            $('input[name=weight_1]').val($(this).val()); $('input[name=weight_2]').val($(this).val()); $('input[name=weight_4]').val($(this).val()); $('input[name=weight_5]').val($(this).val());
        });
        $('input[name=weight_4]').bind("change paste keyup", function() {
            $('input[name=weight_1]').val($(this).val()); $('input[name=weight_2]').val($(this).val()); $('input[name=weight_3]').val($(this).val()); $('input[name=weight_5]').val($(this).val());
        });
        $('input[name=weight_5]').bind("change paste keyup", function() {
            $('input[name=weight_1]').val($(this).val()); $('input[name=weight_2]').val($(this).val()); $('input[name=weight_3]').val($(this).val()); $('input[name=weight_4]').val($(this).val());
        });

        $('select[name=arm_position_1]').bind("change", function() {
            $('select[name=arm_position_5]').val($(this).val());
        });
        $('select[name=arm_position_5]').bind("change", function() {
            $('select[name=arm_position_1]').val($(this).val());
        });

        $('input[name=neck_1]').bind("change paste keyup", function() {
            $('input[name=neck_3]').val($(this).val()); $('input[name=neck_4]').val($(this).val()); $('input[name=neck_5]').val($(this).val());
        });
        $('input[name=neck_3]').bind("change paste keyup", function() {
            $('input[name=neck_1]').val($(this).val()); $('input[name=neck_4]').val($(this).val()); $('input[name=neck_5]').val($(this).val());
        });
        $('input[name=neck_4]').bind("change paste keyup", function() {
            $('input[name=neck_1]').val($(this).val()); $('input[name=neck_3]').val($(this).val()); $('input[name=neck_5]').val($(this).val());
        });
        $('input[name=neck_5]').bind("change paste keyup", function() {
            $('input[name=neck_1]').val($(this).val()); $('input[name=neck_3]').val($(this).val()); $('input[name=neck_4]').val($(this).val());
        });

        $('input[name=chest_1]').bind("change paste keyup", function() {
            $('input[name=chest_3]').val($(this).val()); $('input[name=chest_4]').val($(this).val()); $('input[name=chest_5]').val($(this).val());
        });
        $('input[name=chest_3]').bind("change paste keyup", function() {
            $('input[name=chest_1]').val($(this).val()); $('input[name=chest_4]').val($(this).val()); $('input[name=chest_5]').val($(this).val());
        });
        $('input[name=chest_4]').bind("change paste keyup", function() {
            $('input[name=chest_1]').val($(this).val()); $('input[name=chest_3]').val($(this).val()); $('input[name=chest_5]').val($(this).val());
        });
        $('input[name=chest_5]').bind("change paste keyup", function() {
            $('input[name=chest_1]').val($(this).val()); $('input[name=chest_3]').val($(this).val()); $('input[name=chest_4]').val($(this).val());
        });

        $('input[name=stomach_1]').bind("change paste keyup", function() {
            $('input[name=stomach_3]').val($(this).val()); $('input[name=stomach_4]').val($(this).val()); $('input[name=stomach_5]').val($(this).val());
        });
        $('input[name=stomach_3]').bind("change paste keyup", function() {
            $('input[name=stomach_1]').val($(this).val()); $('input[name=stomach_4]').val($(this).val()); $('input[name=stomach_5]').val($(this).val());
        });
        $('input[name=stomach_4]').bind("change paste keyup", function() {
            $('input[name=stomach_1]').val($(this).val()); $('input[name=stomach_3]').val($(this).val()); $('input[name=stomach_5]').val($(this).val());
        });
        $('input[name=stomach_5]').bind("change paste keyup", function() {
            $('input[name=stomach_1]').val($(this).val()); $('input[name=stomach_3]').val($(this).val()); $('input[name=stomach_4]').val($(this).val());
        });

        $('input[name=nape_to_waist_1]').bind("change paste keyup", function() {
            $('input[name=nape_to_waist_3]').val($(this).val()); $('input[name=nape_to_waist_4]').val($(this).val()); $('input[name=nape_to_waist_5]').val($(this).val());
        });
        $('input[name=nape_to_waist_3]').bind("change paste keyup", function() {
            $('input[name=nape_to_waist_1]').val($(this).val()); $('input[name=nape_to_waist_4]').val($(this).val()); $('input[name=nape_to_waist_5]').val($(this).val());
        });
        $('input[name=nape_to_waist_4]').bind("change paste keyup", function() {
            $('input[name=nape_to_waist_1]').val($(this).val()); $('input[name=nape_to_waist_3]').val($(this).val()); $('input[name=nape_to_waist_5]').val($(this).val());
        });
        $('input[name=nape_to_waist_5]').bind("change paste keyup", function() {
            $('input[name=nape_to_waist_1]').val($(this).val()); $('input[name=nape_to_waist_3]').val($(this).val()); $('input[name=nape_to_waist_4]').val($(this).val());
        });

        $('input[name=front_waist_length_1]').bind("change paste keyup", function() {
            $('input[name=front_waist_length_3]').val($(this).val()); $('input[name=front_waist_length_4]').val($(this).val()); $('input[name=front_waist_length_5]').val($(this).val());
        });
        $('input[name=front_waist_length_3]').bind("change paste keyup", function() {
            $('input[name=front_waist_length_1]').val($(this).val()); $('input[name=front_waist_length_4]').val($(this).val()); $('input[name=front_waist_length_5]').val($(this).val());
        });
        $('input[name=front_waist_length_4]').bind("change paste keyup", function() {
            $('input[name=front_waist_length_1]').val($(this).val()); $('input[name=front_waist_length_3]').val($(this).val()); $('input[name=front_waist_length_5]').val($(this).val());
        });
        $('input[name=front_waist_length_5]').bind("change paste keyup", function() {
            $('input[name=front_waist_length_1]').val($(this).val()); $('input[name=front_waist_length_3]').val($(this).val()); $('input[name=front_waist_length_4]').val($(this).val());
        });

        $('input[name=back_waist_height_2]').bind("change paste keyup", function() {
            $('input[name=back_waist_height_4]').val($(this).val());
        });
        $('input[name=back_waist_height_4]').bind("change paste keyup", function() {
            $('input[name=back_waist_height_2]').val($(this).val());
        });

        $('input[name=front_waist_height_2]').bind("change paste keyup", function() {
            $('input[name=front_waist_height_4]').val($(this).val());
        });
        $('input[name=front_waist_height_4]').bind("change paste keyup", function() {
            $('input[name=front_waist_height_2]').val($(this).val());
        });

        $('input[name=biceps_1]').bind("change paste keyup", function() {
            $('input[name=biceps_3]').val($(this).val()); $('input[name=biceps_4]').val($(this).val()); $('input[name=biceps_5]').val($(this).val());
        });
        $('input[name=biceps_3]').bind("change paste keyup", function() {
            $('input[name=biceps_1]').val($(this).val()); $('input[name=biceps_4]').val($(this).val()); $('input[name=biceps_5]').val($(this).val());
        });
        $('input[name=biceps_4]').bind("change paste keyup", function() {
            $('input[name=biceps_1]').val($(this).val()); $('input[name=biceps_3]').val($(this).val()); $('input[name=biceps_5]').val($(this).val());
        });
        $('input[name=biceps_5]').bind("change paste keyup", function() {
            $('input[name=biceps_1]').val($(this).val()); $('input[name=biceps_3]').val($(this).val()); $('input[name=biceps_4]').val($(this).val());
        });

        $('input[name=back_shoulder_1]').bind("change paste keyup", function() {
            $('input[name=back_shoulder_3]').val($(this).val()); $('input[name=back_shoulder_4]').val($(this).val()); $('input[name=back_shoulder_5]').val($(this).val());
        });
        $('input[name=back_shoulder_3]').bind("change paste keyup", function() {
            $('input[name=back_shoulder_1]').val($(this).val()); $('input[name=back_shoulder_4]').val($(this).val()); $('input[name=back_shoulder_5]').val($(this).val());
        });
        $('input[name=back_shoulder_4]').bind("change paste keyup", function() {
            $('input[name=back_shoulder_1]').val($(this).val()); $('input[name=back_shoulder_3]').val($(this).val()); $('input[name=back_shoulder_5]').val($(this).val());
        });
        $('input[name=back_shoulder_5]').bind("change paste keyup", function() {
            $('input[name=back_shoulder_1]').val($(this).val()); $('input[name=back_shoulder_3]').val($(this).val()); $('input[name=back_shoulder_4]').val($(this).val());
        });

        $('input[name=u_rise_2]').bind("change paste keyup", function() {
            $('input[name=u_rise_auto_2]').val(parseInt($(this).val())-2);
        });
        $('input[name=u_rise_auto_2]').bind("change paste keyup", function() {
            $('input[name=u_rise_2]').val(parseInt($(this).val())+2);
        });

    });
</script>