<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 03/06/2015
 * Time: 17:41
 */
?>

<div class="subHeader">
    Изменить основную информацию:
</div>

<?php
    $monogramFlag = $form->get('product_id')->getValue()=='1' || $form->get('product_id')->getValue()=='5' || $form->get('product_id')->getValue()=='4';

    $form->setAttribute('action', $this->url('seller', array('action' => 'changegen', 'id' => $id)));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    echo $this->form()->openTag($form);
    $form->get('c_id')->setValue($id);
    echo $this->formHidden($form->get('c_id'));
?>

<input name="product_id" style="display: none" value="<?php echo $form->get('product_id')->getValue()?>">
<input name="paytype_id" style="display: none" value="<?php echo $form->get('paytype_id')->getValue()?>">
<input name="order_id" style="display: none" value="<?php echo $form->get('order_id')->getValue()?>">
<input name="preferred_date" style="display: none" value="<?php echo $form->get('preferred_date')->getValue()?>">
<input name="textile_class" style="display: none" value="<?php echo $form->get('textile_class')->getValue()?>">
<!--<input name="pricelistnum" style="display: none" value="--><?php //echo $form->get('pricelistnum')->getValue()?><!--">-->
<input name="actual_amount" style="display: none" value="<?php echo $form->get('actual_amount')->getValue()?>">
<input name="typeof_measure" style="display: none" value="<?php echo $form->get('typeof_measure')->getValue()?>">
<input name="discount_amount" style="display: none" value="<?php echo $form->get('discount_amount')->getValue()?>">

<table class="myTable">
    <tr>
        <td>
            <b>ФИО клиента</b>
        </td>
        <td class="sellerColumn">
            <input style="width: 500px" class="form-control" value="<?php echo $clientName;?>" disabled>
        </td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('style_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('preferred_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo '<input class="form-control" disabled value="'.(explode('-',$form->get('preferred_date')->getValue())[2].'.'.explode('-',$form->get('preferred_date')->getValue())[1].'.'.explode('-',$form->get('preferred_date')->getValue())[0]).'" />'; ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formInput($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>
    </tr>
</table>


<a class="btn btn-default" onclick="goBack()">Отмена</a>
<?php
    echo $this->formSubmit($form->get('orderclothessubmit'));
    echo $this->form()->closeTag();
?>


<script>
    $(function() {


//        product_id
//        seller_comment
        if($('textarea[name=seller_comment]').val()==''){
            switch($('select[name=product_id]').val()){
                case '1': $('textarea[name=seller_comment]').val(
                    'Номер подкладки: \n' +
                    '1)\n2)\n3)\n4)\n5)'
                    ); break; // пиджак
                case '5': $('textarea[name=seller_comment]').val(
                    'Номер подкладки: \n' +
                    '1)\n2)\n3)\n4)\n5)'
                ); break; // пальто

                case '4': $('textarea[name=seller_comment]').val(
                    'Ворот: \n' +
                    'Манжет: \n' +
                    '1)\n2)\n3)\n4)\n5)'
                ); break; // сорочка
                case '9': $('textarea[name=seller_comment]').val(
                    'Ворот: \n' +
                    'Манжет: \n' +
                    '1)\n2)\n3)\n4)\n5)'
                ); break; // Манжет
                case '10': $('textarea[name=seller_comment]').val(
                    'Ворот: \n' +
                    'Манжет: \n' +
                    '1)\n2)\n3)\n4)\n5)'
                ); break; // Ворот

                case '2': $('textarea[name=seller_comment]').val('1)\n2)\n3)\n4)\n5)'); break; // Брюки
                case '3': $('textarea[name=seller_comment]').val('1)\n2)\n3)\n4)\n5)'); break; // жилетка
                case '7': $('textarea[name=seller_comment]').val('Размер шеи: см\n1)\n2)\n3)'); break; // Бабочка
                case '6': $('textarea[name=seller_comment]').val('Брючная талия: см\n1)\n2)\n3)'); break; // Бабочка
            }
        }

        $('textarea[name=seller_comment]').css('width','500px');
        $('textarea[name=seller_comment]').css('height','200px');


        <?php if($form->get('style_id')->getValue()==null){?>
            resetStylesSelect();
        <?php } ?>

        $('select[name=style_id]').prop('required', 'true');

        $('select[name=product_id]').prop('disabled', 'true');

        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());

        $('select[name=typeof_measure]').prop('disabled', 'true');

        $('input[name=textile_id]').prop('readonly', 'readonly');

    });

    function goBack(){
        window.location = '../changeorder';
    }

    function changeCycleDate(){
        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());
    }

    function resetStylesSelect(){
        $.ajax({
            url: '/order/resetstylestoselect',
            type: 'POST',
            dataType: 'json',
            async: true,
            data: { cloth_type_id : $('select[name=product_id]').val() },
            success: function (data) {
                if(data.styles!='empty'){

                    $('select[name=style_id] option').remove();
                    $('select[name=style_id]').append($("<option></option>").attr("value",'0').text('Выберите номер стиля'));

                    for(i=0; i<data.styles.length; i++){
                        $('select[name=style_id]').append($("<option></option>").attr("value",data.styles[i]).text(data.styles[i]));
                    }
                } else {
                    $('select[name=style_id] option').remove();
                    $('select[name=style_id]').append($("<option></option>").attr("value",'0').text('Выберите номер стиля'));
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
</script>