<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 03/06/2015
 * Time: 17:41
 */
?>

<div class="subHeader">
    Изменить основную информацию:
</div>

<?php
    $monogramFlag = $form->get('product_id')->getValue()!='2' && $form->get('product_id')->getValue()!='4';

    $form->setAttribute('action', $this->url('seller', array('action' => 'changegen', 'id' => $id)));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    echo $this->form()->openTag($form);
    $form->get('c_id')->setValue($id);
    echo $this->formHidden($form->get('c_id'));
?>

<input name="product_id" style="display: none" value="<?php echo $form->get('product_id')->getValue()?>">
<input name="paytype_id" style="display: none" value="<?php echo $form->get('paytype_id')->getValue()?>">
<input name="order_id" style="display: none" value="<?php echo $form->get('order_id')->getValue()?>">
<input name="preferred_date" style="display: none" value="<?php echo $form->get('preferred_date')->getValue()?>">
<input name="textile_class" style="display: none" value="<?php echo $form->get('textile_class')->getValue()?>">
<input name="pricelistnum" style="display: none" value="<?php echo $form->get('pricelistnum')->getValue()?>">
<input name="actual_amount" style="display: none" value="<?php echo $form->get('actual_amount')->getValue()?>">
<input name="typeof_measure" style="display: none" value="<?php echo $form->get('typeof_measure')->getValue()?>">

<table class="myTable">
    <tr>
        <td>
            <b>ФИО клиента</b>
        </td>
        <td class="sellerColumn">
            <input style="width: 300px" class="form-control" value="<?php echo $clientName;?>" disabled>
        </td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('style_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('preferred_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>
    </tr>
</table>

<a class="btn btn-default" onclick="goBack()">Отмена</a>
<?php
    echo $this->formSubmit($form->get('orderclothessubmit'));
    echo $this->form()->closeTag();
?>


<script>
    $(function() {
        $('select[name=product_id]').prop('disabled', 'true');

        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());
    });

    function goBack(){
        window.location = '../changeorder';
    }
</script>