<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 08/06/2015
 * Time: 19:15
 */
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Изделия в пути (до Астаны)
</div>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="cycleCol" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл</th>
            <th data-column-id="customer_full_name">Клиент</th>
            <th data-header-css-class="clothCol" data-column-id="clother">Изделие</th>
            <!--            <th data-column-id="fabric_class">Класс ткани</th>-->
            <!--            <th data-header-css-class="fabricCol" data-type="numeric" data-column-id="textile_id">Ткань</th>-->
            <th data-type="datetime" data-header-css-class="wishDateCol" data-column-id="dateofsale">Продажа</th>
            <th data-type="datetime" data-header-css-class="wishDateCol" data-column-id="preferred_date">Wish date</th>
            <th data-type="datetime" data-header-css-class="wishDateCol2" data-column-id="cycle_date">Дост. цикл</th>
            <th data-column-id="seller_full_name">Продавец</th>

            <th data-header-css-class="sellerColumnBtn2" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<div id="myModal" style="display: none; text-align: center">

    <input style="display: none" id="order_cloth_id" />
    <input style="display: none" id="customer_full_name" />
    <input style="display: none" id="cloth_type" />
    <input style="display: none" id="seller_full_name" />
    <input style="display: none" id="date_of_sale" />
    <input style="display: none" id="preferred_date" />
    <input style="display: none" id="cycle_id" />
    <input style="display: none" id="cycle_date" />

    <table style="width: 100%; text-align: left;">
        <tr>
            <td><span style="text-decoration: underline">Комментарии</span> <br />(соответствует ли прибывшое изделие заказу клиента):</td>
            <td><textarea required="true" id="comment" class="form-control"></textarea></td>
        </tr>
    </table>

    <button onclick="closeDlg()" class="btn btn-default" style="margin-top: 8px; margin-right:10px;">Отмена</button>
    <button onclick="setArrived();" class="btn btn-primary" style="margin-top: 8px;">Подтвердить</button>

</div>

<script>
    $(function () {

        $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd'});

        function init() {
            var grid = $("#order-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '<?php echo $current_user_id;?>',
                        order_status: 6
                    };
                },
                url: "/restorderclothes",
                converters: {
                    datetime: {
                        from: function (value) { return value; },
                        to: function (value) {
                            temp = value.split('-');
                            return temp[2]+'/'+temp[1]+'/'+temp[0];
                        }
                    }
                },
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type='button' class='btn btn-xs btn-primary enterCodes' " +
                                "data-row-customer_full_name=\"" + row.customer_full_name + "\"" +
                                "data-row-cloth_type=\"" + row.clother + "\"" +
                                "data-row-seller_full_name=\"" + row.seller_full_name + "\"" +
                                "data-row-date_of_sale=\"" + row.dateofsale + "\"" +
                                "data-row-preferred_date=\"" + row.preferred_date + "\"" +
                                "data-row-cycle_id=\"" + row.cycle_id + "\"" +
                                "data-row-cycle_date=\"" + row.cycle_date + "\"" +
                                "data-row-id=\"" + row.my_id + "\">Подтвердить <br /> доставку</button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".enterCodes").on("click", function(e)
                {
                    $('#customer_full_name').val($(this).data("row-customer_full_name"));
                    $('#cloth_type').val($(this).data("row-cloth_type"));
                    $('#seller_full_name').val($(this).data("row-seller_full_name"));
                    $('#date_of_sale').val($(this).data("row-date_of_sale"));
                    $('#preferred_date').val($(this).data("row-preferred_date"));
                    $('#cycle_id').val($(this).data("row-cycle_id"));
                    $('#cycle_date').val($(this).data("row-cycle_date"));

                    openDlg($(this).data("row-id"));
                });
            });
        }
        init();
    });

    function openDlg(id){

        $('#order_cloth_id').val(id);
        $('#comment').css('width','300px');
        $('#comment').val('Замечании нет.');

        $('#myModal').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 600,
            height: 200,
            title: 'Подтвердить прибытие изделия в офис'
        });
    }

    function closeDlg(){
        $('#myModal').dialog('close');
    }

    function setArrived(){
        if($('#order_cloth_id').val()!='')

            var customer_full_name = $('#customer_full_name').val();
            var cloth_type = $('#cloth_type').val();
            var seller_full_name = $('#seller_full_name').val();
            var date_of_sale = convertDate($('#date_of_sale').val());
            var preferred_date = convertDate($('#preferred_date').val());
            var cycle_id = $('#cycle_id').val();
            var cycle_date = convertDate($('#cycle_date').val());

            var comment = 'Клиент: ' + customer_full_name +
                            '<br> Изделие: ' + cloth_type +
                            '<br> Продавец: ' + seller_full_name +
                            '<br> Дата продажи: ' + date_of_sale +
                            '<br> Предпочтительная дата выдачи: ' + preferred_date +
                            '<br> Цикл: ' + cycle_id +
                            '<br> Дата прибытие по циклу: ' + cycle_date +
                            '<br> Доставлено '+getToday()+': '+$('#comment').val();

            $.post( "setarrived", { id: $('#order_cloth_id').val(), comment: comment} ).done(function( data ) {
                closeDlg();
                $('#order-grid').bootgrid('reload');
            });
    }

    function getToday(){
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth()+1; //January is 0!

        var yyyy = today.getFullYear();
        if(dd<10){
            dd='0'+dd
        }
        if(mm<10){
            mm='0'+mm
        }
        var today = dd+'/'+mm+'/'+yyyy;

        return today;
    }

    function convertDate(value) {
        temp = value.split('-');
        return temp[2] + '/' + temp[1] + '/' + temp[0];
    }
</script>