<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 27/05/2015
 * Time: 23:14
 */

$monogramFlag = $form->get('product_id')->getValue()!='2' && $form->get('product_id')->getValue()!='4';

$form->setAttribute('action', $this->url('seller', array('action' => 'orderdenychange', 'id' => $id)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
$form->get('c_id')->setValue($id);
echo $this->formHidden($form->get('c_id'));

//$en_form->setAttribute('class', 'form-horizontal');
//$en_form->prepare();
//echo $this->form()->openTag($en_form);

?>

<div class="header">
    Проверить изделие
</div>

<table class="myTable">
    <tr>
        <td colspan="2" style="padding-bottom: 15px; text-decoration: underline; font-weight: bold;"><div class="subHeader">Данные введенные продавцом:</div></td>
        <td colspan="2" style="padding-bottom: 15px; text-decoration: underline; font-weight: bold;"><div class="subHeader">Данные введенные редактором:</div></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('cloth_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('measurement_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('style_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="sellerColumn"><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('style_id'); ?>
            <b>Style number</b>
        </td>
        <td class="disabledColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <b>Cycle number</b>
        </td>
        <td class="disabledColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <b>Arrival date</b>
        </td>
        <td class="disabledColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('fabric_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('brand_label'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php echo $this->formSelect($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>

        <td>
            <?php $element = $en_form->get('redactor_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td class="disabledColumn"><?php echo $this->formTextArea($element); ?></td>
    </tr>
</table>

<hr>

<div class="subHeader">
    Замеры сделанные продавцом по <?php if($measurement_type==1) echo "фигуре"; else echo "изделию"; ?>:
</div>

<input name='paytype_id' style="display: none" value='<?php echo $form->get('paytype_id')->getValue();?>'/>

<?php
if($measurement_type==1){
    $bm_form->setAttribute('class', 'form-horizontal');
    $bm_form->prepare();
    echo $this->form()->openTag($bm_form);
    echo $this->formHidden($bm_form->get('id'));
    echo $this->formHidden($bm_form->get('clother_id'));
    echo $this->formHidden($bm_form->get('customer_id'));
    ?>
    <table class="measureTable">
        <tr>
            <td>
                <?php $element = $bm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('arm_position'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('butt_position'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('neck'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('chest'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('stomach'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('seat'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('thigh'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('knee_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('pant_bottom_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('u_rise'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('u_rise_auto'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('otseam_l_and_r'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('nape_to_waist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('front_waist_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_waist_height'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('front_waist_height'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('biceps'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_shoulder'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('right_sleeve'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('left_sleeve'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('overcoat_back_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('waist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('right_wrist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('left_wrist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('style'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>
        </tr>
    </table>
    <?php
//    echo $this->form()->closeTag();
} else {
    $cm_form->setAttribute('class', 'form-horizontal');
    $cm_form->prepare();
    echo $this->form()->openTag($cm_form);
    echo $this->formHidden($cm_form->get('id'));
    ?>
    <table class="measureTable">
        <tr>
            <td>
                <?php $element = $cm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('chest_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('stomach_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('jacket_seat_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('biceps_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('left_sleeve_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('right_sleeve_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('back_length_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('front_length_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('shoulder_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('waist_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('seat_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('thigh_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('outseam_l_and_r_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('knee_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('pant_bottom_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('u_rise_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('right_cuff'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('left_cuff'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('shirt_neck'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
    </table>
    <?php
//    echo $this->form()->closeTag();
}
?>

<hr>
<div class="subHeader">
    Системные коды введенные редактором:
</div>
<div id="testModel">
    <?php
    $sc_form->setAttribute('class', 'form-horizontal');
    $sc_form->prepare();
    echo $this->form()->openTag($sc_form);
    $systemCodeForm = $sc_form->get('systemcode');
    echo $this->formCollection($systemCodeForm);
    echo $this->formHidden($sc_form->get('csrf'));
//    echo $this->form()->closeTag($sc_form);
    ?>
</div>

<hr>

<a class="btn btn-default" onclick="goBack()">Отмена</a>

<?php
    echo $this->formSubmit($bm_form->get('submit'));
    echo $this->formSubmit($form->get('orderclothessubmit'));
    echo $this->form()->closeTag();
?>

<script>
    $(function() {

        $('select[name=cycle_date]').val($('select[name=cycle_id]').val());

        $('.disabledColumn').find('input').attr('disabled', 'true');
        $('.disabledColumn').find('select').attr('disabled', 'true');
        $('.disabledColumn').find('textarea').attr('disabled', 'true');

        $('#testModel').find('input').attr('disabled', 'true');
        $('#testModel').find('select').attr('disabled', 'true');
        $('#testModel').find('textarea').attr('disabled', 'true');

        $('.measureTable').find('input').removeAttr('disabled');
        $('.measureTable').find('select').removeAttr('disabled');
        $('.measureTable').find('textarea').removeAttr('disabled');

        $("button:contains('Удалить строку')").remove();

        styleRows();

        var fieldsets = $('#testModel').find('fieldset');
        for(i=0; i<fieldsets.length; i++){
            if(i!=0 && i!=1) $(fieldsets[i]).find('span').remove();
        }
    });

    function styleRows(){
        $('#testModel').find('fieldset').find('label').css('margin-right', '20px');
    }

    function goBack(){
        window.location = '../orderstocheck';
    }

</script>