<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 26/05/2015
 * Time: 16:12
 */
?>

<div class="header">
    Список тканей
</div>

<div class="col-md-9">
    <table id="fabric-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-column-id="fabric_class">Класс ткани</th>
            <th data-column-id="fabric_available_start_date" data-order="desc">Дата наличия ткани</th>
        </tr>
        </thead>

    </table>
</div>

<script>
    $(function () {
        function init() {
            var grid = $("#fabric-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restfabric"
            });
        }
        init();
    })

</script>