<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 26/05/2015
 * Time: 21:02
 */
?>

<div class="header">
    Изделия отправленные редактором для проверки
</div>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="cycleCol" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл</th>
            <th data-column-id="customer_full_name">Клиент</th>
            <th data-header-css-class="clothCol" data-column-id="clother">Изделие</th>
            <th data-column-id="textile_id">Ткань</th>
            <!--            <th data-column-id="fabric_class">Класс ткани</th>-->
            <!--            <th data-header-css-class="fabricCol" data-type="numeric" data-column-id="textile_id">Ткань</th>-->
            <th data-type="datetime" data-header-css-class="wishDateCol" data-column-id="dateofsale">Продажа</th>
            <th data-type="datetime" data-header-css-class="wishDateCol" data-column-id="preferred_date">Wish date</th>
            <th data-type="datetime" data-header-css-class="wishDateCol2" data-column-id="cycle_date">Дост. цикл</th>
            <th data-column-id="seller_full_name">Продавец</th>

            <th data-header-css-class="sellerColumnBtn" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script>
    $(function () {

        hideMenu();

        function init() {
            var grid = $("#order-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '<?php echo $current_user_id;?>',
                        order_status: 3
                    };
                },
                url: "/restorderclothes",
                converters: {
                    datetime: {
                        from: function (value) { return value; },
                        to: function (value) {
                            temp = value.split('-');
                            return temp[2]+'/'+temp[1]+'/'+temp[0];
                        }
                    }
                },
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-primary enterCodes\" data-row-id=\"" + row.my_id + "\">Проверить</button><br />";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".enterCodes").on("click", function(e)
                {
                    window.location="orderstocheck/"+$(this).data("row-id");
                });
            });
        }
        init();
    })
</script>