<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 27/05/2015
 * Time: 23:14
 */

    $monogramFlag = $form->get('product_id')->getValue()!='2' && $form->get('product_id')->getValue()!='4';
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Проверить изделие
</div>

<table class="myTable">
    <tr>
        <td colspan="2" style="padding-bottom: 15px; text-decoration: underline; font-weight: bold;"><div class="subHeader">Данные введенные продавцом:</div></td>
        <td colspan="2" style="padding-bottom: 15px; text-decoration: underline; font-weight: bold;"><div class="subHeader">Данные введенные редактором:</div></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('cloth_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('measurement_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('style_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('style_id'); ?>
            <b>Style number</b>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <b>Cycle number</b>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $form->get('cycle_date'); ?>
            <b>Arrival date</b>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('fabric_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php $element = $form->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('brand_label'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>
    <tr>
        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>

        <td>
            <?php $element = $en_form->get('redactor_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formTextArea($element); ?></td>
    </tr>
</table>

<hr>

<div class="subHeader">
    Замеры сделанные продавцом по <?php if($measurement_type==1) echo "фигуре"; else echo "изделию"; ?>:
</div>

<?php
if($measurement_type==1){
    $bm_form->setAttribute('class', 'form-horizontal');
    $bm_form->prepare();
    echo $this->form()->openTag($bm_form);
    ?>
    <table class="myTable">
        <tr>
            <td>
                <?php $element = $bm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('arm_position'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('butt_position'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('neck'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('chest'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('stomach'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('seat'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('thigh'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('knee_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('pant_bottom_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('u_rise'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('u_rise_auto'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('otseam_l_and_r'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('nape_to_waist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('front_waist_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_waist_height'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('front_waist_height'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('biceps'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_shoulder'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('right_sleeve'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('left_sleeve'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('back_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('overcoat_back_length'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('waist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('right_wrist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('left_wrist'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('style'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
} else {
    ?>
    <?php
    $cm_form->setAttribute('class', 'form-horizontal');
    $cm_form->prepare();
    echo $this->form()->openTag($cm_form);
    ?>
    <table class="myTable">
        <tr>
            <td>
                <?php $element = $cm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('chest_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('stomach_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('jacket_seat_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('biceps_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('left_sleeve_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('right_sleeve_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('back_length_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('front_length_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('shoulder_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('waist_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('seat_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('thigh_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('outseam_l_and_r_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('knee_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('pant_bottom_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('u_rise_finished'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('right_cuff'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('left_cuff'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('shirt_neck'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
}
?>

<hr>
<div class="subHeader">
    Системные коды введенные редактором:
</div>
<div id="testModel">
    <?php
    $sc_form->setAttribute('class', 'form-horizontal');
    $sc_form->prepare();
    echo $this->form()->openTag($sc_form);
    $systemCodeForm = $sc_form->get('systemcode');
    echo $this->formCollection($systemCodeForm);
    echo $this->formHidden($sc_form->get('csrf'));
    echo $this->form()->closeTag();
    ?>
</div>

<hr>
<a class="btn btn-danger" onclick="denyDlg()">Откатить назад</a>
<a class="btn btn-danger" onclick="denyWithChange()">Откатить назад с исправлением</a>
<a class="btn btn-success" onclick="confirmDlg()">Подтвердить</a>

<div id="denyDlg" style="display: none; font-weight: bold;">
    Вы дейстивтельно хотите откатить назад к редактору даное изделие?<br /><br />
    Ваш комментарии: <textarea id="denyDlgText"></textarea>
    <span id="denyError" style="color: red;"></span>

    <div style="text-align: center; margin-top: 10px;">
        <a class="btn btn-default" style="margin: 5px;" onclick="$('#denyDlg').dialog('close');">Отмена</a>
        <a class="btn btn-danger" style="margin: 5px;" onclick="deny()">Откатить</a>
    </div>
</div>
<div id="denyWithChangeDlg" style="display: none;">
</div>
<div id="confirmDlg" style="display: none; font-weight: bold;">
    Вы действительно подтверждаете:
    <ul>
        <li>верность данных введенных продавцом,</li>
        <li>верность даннных введенных редактором,</li>
        <li>верность замеров,</li>
        <li>верность системных кодов?</li>
    </ul>
    <div style="text-align: center;">
        <a class="btn btn-default" style="margin: 5px;" onclick="$('#confirmDlg').dialog('close');">Нет</a>
        <a class="btn btn-success" style="margin: 5px;" onclick="confirm()">Да</a>
    </div>
</div>

<script>
    $(function() {
        $('input').attr('disabled', 'true');
        $('select').attr('disabled', 'true');
        $('textarea').attr('disabled', 'true');

        $('button').remove();

        styleRows();

        var fieldsets = $('#testModel').find('fieldset');
        for(i=0; i<fieldsets.length; i++){
            if(i!=0 && i!=1) $(fieldsets[i]).find('span').remove();
        }
    });

    function styleRows(){
        $('#testModel').find('fieldset').find('label').css('margin-right', '20px');
    }

    function confirmDlg(){
        $('#confirmDlg').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 470,
            height: 230
        });
    }

    function denyDlg(){
        $('#denyDlgText').removeAttr('disabled');
        $('#denyDlg').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 470,
            height: 230
        });
    }

    function denyWithChange(){
        window.location = '../orderdenychange/'+window.location.href.split('/')[window.location.href.split('/').length-1];
    }

    function confirm(){
        window.location = '../orderconfirm/'+window.location.href.split('/')[window.location.href.split('/').length-1];
    }

    function deny(){
        if($('#denyDlgText').val()=='')
            $('#denyError').text('Напишите причину отката данного изделия');
        else
            window.location = '../orderrollback?id='+window.location.href.split('/')[window.location.href.split('/').length-1]+'&comment='+$('#denyDlgText').val();
    }
</script>