<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 26/05/2015
 * Time: 21:05
 */
?>

<div class="header">
    Изделия на примерке
</div>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="redactorNumColumns" data-type="numeric" data-column-id="order_id">#Заказа</th>
            <th data-column-id="customer_full_name">Клиент</th>
            <th data-header-css-class="redactorClothColumn" data-column-id="clother">Изделие</th>
            <th data-column-id="fabric_class">Класс ткани</th>
            <th data-header-css-class="redactorNumColumns" data-type="numeric" data-column-id="textile_id">#Ткани</th>
            <th data-header-css-class="redactorNumColumns" data-type="numeric" data-column-id="cycle_id">#Цикла</th>
            <th data-column-id="dateofsale">Дата продажи</th>
            <!--            <th data-column-id="seller_full_name" data-order="desc">Продовец</th>-->
            <th data-column-id="status_name" data-order="desc">Статус</th>
            <th data-column-id="redactor_notes" data-order="desc">Заметки редактора</th>

            <th data-header-css-class="sellerColumnBtn3" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<script>
    $(function () {

        function init() {
           var grid = $("#order-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '<?php echo $current_user_id;?>',
                        order_status: 8
                    };
                },
                url: "/restorderclothes",
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary IrinaTook\" data-row-id=\"" + row.order_id + "\">Ирина забрала</button><br />" +
                            "<button data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary MayaTook\" data-row-id=\"" + row.order_id + "\">Мая забрала</button><br />" +
                            "<button data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary ClientTook\" data-row-id=\"" + row.order_id + "\">Выдали</button>";

                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".IrinaTook").on("click", function(e)
                {
                    var myId = $(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы уверены что данное изделие было отправлено потрному - Ирина?", function(result) {
                        if(result){
                            window.location ='givetotailor?id='+myId+'&tailor_id=1';
                        }
                    });
                }).end().find(".MayaTook").on("click", function(e)
                {
                    var myId = $(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы уверены что данное изделие было отправлено потрному - Мая?", function(result) {
                        if(result){
                            window.location ='givetotailor?id='+myId+'&tailor_id=2';
                        }
                    });
                }).end().find(".ClientTook").on("click", function(e)
                {
                    var myId = $(this).data("row-id");
                    bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });
                    bootbox.confirm("Вы уверены что данное изделие было выдано клиенту?", function(result) {
                        if(result){
                            window.location ='givetoclient?id='+myId;
                        }
                    });
                });
            });
        }

        init();
    })
</script>