<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 26/05/2015
 * Time: 21:05
 */
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Изделия в офисе (приглашенные на примерку)
</div>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="cycleCol" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл</th>
            <th data-column-id="customer_full_name">Клиент</th>
            <th data-header-css-class="clothCol" data-column-id="clother">Изделие</th>
            <th data-column-id="textile_id">Ткань</th>
            <!--            <th data-column-id="fabric_class">Класс ткани</th>-->
            <!--            <th data-header-css-class="fabricCol" data-type="numeric" data-column-id="textile_id">Ткань</th>-->
            <th data-type="datetime"  data-column-id="dateofsale">Продажа</th>
            <th data-type="datetime"  data-column-id="preferred_date">Wish date</th>
            <th data-type="datetime"  data-column-id="cycle_date">Дост. цикл</th>
            <th data-type="datetime" data-column-id="arrival_date">Дост. факт</th>
            <th data-type="datetime" data-column-id="fitting_date">Примерка</th>
<!--            <th data-column-id="arrival_comment">Дост. комм</th>-->
            <th data-column-id="seller_full_name">Продавец</th>

            <th data-header-css-class="sellerColumnBtn3" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>

<div id="tracking" style="display: none;">
</div>

<div id="sendToTailor" style="display: none;">

    <input style="display: none;" id="orderclothid" />
    <input style="display: none;" id="tailorid" />
    <input style="display: none;" id="oldComment" />

    Выберите портного:

    <select id="tailor_id" class="form-control" style="width: 250px; display: inline">
        <option value="0">Не выбрано</option>
    <?php
        foreach($this->tailors as $key => $item){
            echo '<option value="'.$key.'">'.$item.'</option>';
        }
    ?>
    </select>
    <br>

    И напишите замечания по изделию, которые возникли во время примерки и перечислите корректировки, которые должен сделать портной:

    <br /><textarea style="height: 110px; margin-top: 10px;" id="sendComments" class="form-control"></textarea>

    <br /><span style="color: red;" id="error"></span>

    <div style="text-align: center; margin-top: 10px;">
        <a class="btn btn-default" onclick="closeDlg()">Отмена</a>
        <a class="btn btn-primary" onclick="sendToTailor()">Отправить</a>
    </div>

</div>

<div id="giveToClient" style="display: none;">
    <input style="display: none;" id="orderclothid1" />
    <input style="display: none;" id="oldComment1" />

    Оставьте отзыв о посадке изделия: <br>
    <ol>
        <li>оцените по 10 бальной шкале</li>
        <li>оцените работу портного</li>
        <li>советы на будущие изделия</li>
    </ol>

    <textarea id="lastComment" class="form-control" style="height: 110px; margin-top: 10px;"></textarea>

    <br /><span style="color: red;" id="error2"></span>

    <div style="text-align: center;">
        <button onclick="closeSendDlg()" class="btn btn-default">Отмена</button>
        <button onclick="sentToClient()" class="btn btn-primary">Отправить</button>
    </div>

</div>

<script>
    $(function () {

        hideMenu();

        function init() {
           var grid = $("#order-grid").bootgrid({
               rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '<?php echo $current_user_id;?>',
                        order_status: 8
                    };
                },
                url: "/restorderclothes",
                converters: {
                   datetime: {
                       from: function (value) { return value; },
                       to: function (value) {
                           temp = value.split('-');
                           return temp[2]+'/'+temp[1]+'/'+temp[0];
                       }
                   }
                },
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button data-row-comment='"+row.arrival_comment+"' data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary IrinaTook\" data-row-id=\"" + row.my_id + "\">Отдали портному</button><br />" +
                            "<button data-row-comment='"+row.arrival_comment+"' data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary inOffice\" data-row-id=\"" + row.my_id + "\">В офисе</button><br />" +
                            "<button data-row-comment='"+row.arrival_comment+"' data-row-fullname='"+row.lastname+" "+row.middlename+" "+row.firstname+"' type=\"button\" class=\"btn btn-xs btn-primary ClientTook\" data-row-id=\"" + row.my_id + "\">Выдали</button><br />"+
                            "<button data-row-comment='"+row.arrival_comment+"' type=\"button\" class=\"btn btn-xs btn-primary showComment\">Показать отчёт</button><br />";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".IrinaTook").on("click", function(e)
                {
                    openDlg($(this).data("row-id"), 1, $(this).data("row-comment"));
                }).end().find(".ClientTook").on("click", function(e)
                {
                    showFinalDlg($(this).data("row-id"), $(this).data("row-comment"));
                }).end().find(".showComment").on("click", function(e)
                {
                    showCommentDlg($(this).data("row-comment"));
                }).end().find(".inOffice").on("click", function(e)
                {
                    inOffice($(this).data("row-id"));
                })
                ;
            });
        }

        init();
    })

    function showCommentDlg(comment){

        $('#tracking').html(comment);

        $('#tracking').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 500,
            height: 335,
            title: 'Комментарий'
        });
    }

    function openDlg(id, tailorid, comment){

        $('#orderclothid').val(id);
        $('#tailorid').val(tailorid);
        $('#oldComment').val(comment);

        $('#sendToTailor').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 500,
            height: 360,
            title: 'Отправить портному'
        });
    }

    function showFinalDlg(id, comment){
        $('#orderclothid1').val(id);
        $('#oldComment1').val(comment);

        $('#giveToClient').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 500,
            height: 335,
            title: 'Выдать клиенту'
        });
    }

    function sendToTailor(){

        if($('#tailor_id').val()==0){
            $('#error').text('Выберите портного');
        } else if($('#sendComments').val()==''){
            $('#error').text('Комментрий не может быть пустым');
        } else{
            $('#error').text('');

            $.post( "givetotailor", { id: $('#orderclothid').val(), comment: $('#oldComment').val()+"<br> Была примерка "+ getToday() + ": " + $('#sendComments').val(), tailor_id: $('#tailor_id').val() } ).done(function( data ) {
                closeDlg();
                $('#order-grid').bootgrid('reload');
            });

        }
    }

    function inOffice(id){
        $.post( "setstatus7", { id: id } ).done(function( data ) {
            $('#order-grid').bootgrid('reload');
        });
    }

    function getToday(){
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth()+1; //January is 0!

        var yyyy = today.getFullYear();
        if(dd<10){
            dd='0'+dd
        }
        if(mm<10){
            mm='0'+mm
        }
        var today = dd+'/'+mm+'/'+yyyy;

        return today;
    }

    function closeDlg(){
        $('#error').text('');
        $('#sendToTailor').dialog('close');
        $('#tailor_id').val(0);
    }

    function closeSendDlg(){
        $('#error2').text('');
        $('#giveToClient').dialog('close');
    }

    function sentToClient(){
        if($('#lastComment').val()==''){
            $('#error2').text('Комментрий не может быть пустым');
        } else{

            $.post( "givetoclient", { id: $('#orderclothid1').val(), comment: $('#oldComment1').val()+"<br> Изделие выдано "+ getToday() + ": " + $('#lastComment').val() } ).done(function( data ) {
                closeSendDlg();
                $('#order-grid').bootgrid('reload');
            });
        }
    }

</script>