<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 26/05/2015
 * Time: 21:06
 */
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Изделия у портных
</div>

<div class="col-md-9">
    <table id="order-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="cycleCol" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл</th>
            <th data-column-id="customer_full_name">Клиент</th>
            <th data-header-css-class="clothCol" data-column-id="clother">Изделие</th>
            <th data-column-id="textile_id">Ткань</th>
            <!--            <th data-column-id="fabric_class">Класс ткани</th>-->
            <!--            <th data-header-css-class="fabricCol" data-type="numeric" data-column-id="textile_id">Ткань</th>-->
            <th data-type="datetime"  data-column-id="dateofsale">Продажа</th>
            <th data-type="datetime"  data-column-id="preferred_date">Wish date</th>
            <th data-type="datetime"  data-column-id="cycle_date">Дост. цикл</th>
            <th data-type="datetime" data-column-id="arrival_date">Дост. факт</th>
            <th data-type="datetime" data-column-id="fitting_date">Примерка</th>
<!--            <th data-column-id="arrival_comment">Дост. комм</th>-->
            <th data-column-id="seller_full_name">Продавец</th>
            <th data-column-id="tailor_name">Портной</th>

            <th data-header-css-class="sellerColumnBtn5" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

        </tr>
        </thead>

    </table>
    <!--/div-->
</div>


<div id="myModal" style="display: none; text-align: center">

    <input style="display: none" id="order_cloth_id" />
    <input style="display: none;" id="oldComment" />
    <input style="display: none;" id="tailorName" />

    <table style="width: 100%; text-align: left;">
        <tr>
            <td><span style="text-decoration: underline">Комментарии</span> <br />(соответствует ли прибывшое изделие заказу клиента):</td>
            <td><textarea required="true" id="comment" class="form-control"></textarea></td>
        </tr>
    </table>

    <button onclick="closeDlg()" class="btn btn-default" style="margin-top: 8px; margin-right:10px;">Отмена</button>
    <button onclick="setArrived();" class="btn btn-primary" style="margin-top: 8px;">Подтвердить</button>

</div>

<div id="tracking" style="display: none;">
</div>

<script>
    $(function () {

        hideMenu();

        $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd'});

        function init() {
            var grid = $("#order-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '<?php echo $current_user_id;?>',
                        order_status: 12
                    };
                },
                url: "/restorderclothes",
                converters: {
                    datetime: {
                        from: function (value) { return value; },
                        to: function (value) {
                            temp = value.split('-');
                            return temp[2]+'/'+temp[1]+'/'+temp[0];
                        }
                    },
                    tailor: {
                        from: function (value) { return value; },
                        to: function (value) {
                            switch(value){
                                case '1': return 'Ирина'; break;
                                case '2': return 'Майя'; break;
                            }
                        }
                    }
                },
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-primary enterCodes\" data-row-comment='"+row.arrival_comment+"' data-row-tailor='"+row.tailor_name+"'  data-row-id=\"" + row.my_id + "\">Портной вернул <br /> в офис</button><br />"+
                            "<button data-row-comment='"+row.arrival_comment+"' type=\"button\" class=\"btn btn-xs btn-primary showComment\">Показать отчёт</button><br />";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".enterCodes").on("click", function(e)
                {
                    openDlg($(this).data("row-id"), $(this).data("row-comment"), $(this).data("row-tailor"));
                }).end().find(".showComment").on("click", function(e)
                {
                    showCommentDlg($(this).data("row-comment"));
                });
            });
        }
        init();
    });

    function openDlg(id, comment, tailorId){

        $('#order_cloth_id').val(id);
        $('#comment').css('width','300px');
        $('#comment').val('Все корректировки выполнены');
        $('#oldComment').val(comment);
        $('#tailorName').val(tailorId);

        $('#myModal').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 600,
            height: 200,
            title: 'Подтвердить прибытие изделия в офис'
        });
    }

    function closeDlg(){
        $('#myModal').dialog('close');
    }

    function setArrived(){
        if($('#order_cloth_id').val()!='')
            $.post( "setarrived", { id: $('#order_cloth_id').val(), comment: $('#oldComment').val() +'<br>' +$('#tailorName').val()+' вернула '+getToday()+': '+ $('#comment').val() } ).done(function( data ) {
                closeDlg();
                $('#order-grid').bootgrid('reload');
            });
    }

    function showCommentDlg(comment){
        $('#tracking').html(comment);

        $('#tracking').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 500,
            height: 335,
            title: 'Комментарий'
        });
    }

    function getToday(){
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth()+1; //January is 0!

        var yyyy = today.getFullYear();
        if(dd<10){
            dd='0'+dd
        }
        if(mm<10){
            mm='0'+mm
        }
        var today = dd+'/'+mm+'/'+yyyy;

        return today;
    }
</script>