<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 03.04.2015
 * Time: 14:59
 */

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formCollection($form);
?>
<table>
    <tr>
        <td>
            <?php echo $this->formHidden($form->get('id')); ?>
            <?php echo $this->formRow($form->get('title'));?>
        </td>
    </tr>
    <tr>
        <td>
            <?php echo $this->formRow($form->get('artist'));?>
        </td>
    </tr>
    <tr>
        <td>
            <?php echo $this->formSubmit($form->get('submit'));?>
        </td>
    </tr>

</table>

<?php echo $this->form()->closeTag();?>

