<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 05.04.2015
 * Time: 14:47
 */

$title = 'Pidzhak';
$this->headTitle($title);
?>

<div id="container">
    <a href="#" class="mainButton">ПРОДАВЕЦ</a>
    <a href="#" class="mainButton">РЕДАКТОР</a>
    <br />
    <a href="#" class="mainButton">БУХГАЛТЕР</a>
    <a href="#" class="mainButton">ДИРЕКТОР</a>
    <br />
    <a href="#" class="mainButton">КУРЬЕР</a>
    <a href="#" class="mainButton">АДМИНИСТРАТОР</a>
</div>