<?php echo $this->doctype();?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PidzhakSOFT') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/jquery.bootgrid.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootbox.min.js'))
            ->prependFile($this->basePath('js/jquery.bootgrid.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.maskedinput.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><img src="<?php echo $this->basePath('img/header-logo.png') ?>" height="80" style="cursor:pointer; padding: 5px; padding-bottom: 10px;" onclick="window.location='<?php echo $this->url('home') ?>'"/></li>
                    </ul>
                    <div id="logoutDiv">
                        <?php if($this->identity()!=null) { ?>
                            <span id="welcomeText">
                                Добро пожаловать, <?php echo $this->identity()['surname']." ".$this->identity()['name']; ?>!
                            </span>
                            <a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">ВЫЙТИ</a>
                        <?php } ?>

                    </div>
                </div>

            </div>
        </nav>
        <div class="container">

        <?php
        if($this->identity()==null)
            echo $this->content;
        else {
            ?>

            <div class="myContainer">
                <div class="left-menu">
                    <?php

                    $sellerMenu = '
                            <button id="hideBtn" class="btn btn-default" onclick="hideMenu();"><span style="top: 2px;" class="glyphicon glyphicon-arrow-left"></span> Скрыть меню </button>

                            <a class="menuBtn header" href="#">Календарь</a>
                            <a class="menuBtn child" href="/seller/myday">Мой день</a>

                            <a class="menuBtn header" href="#">Звонки</a>
                            <a class="menuBtn child" href="/seller/createcall">Создать новый звонок</a>
                            <a class="menuBtn child" href="/seller/calls">Звонки</a>

                            <a class="menuBtn header" href="#">Мои заказы</a>
                            <a class="menuBtn child" href="/customer/firststep">1. Создать новый заказ</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/seller/fillmeasure">1.1. Редактировать замеры</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/seller/changeorder">1.2. Редактировать изделия</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/seller/orderstocheck">1.3. Проверить изделия</a>
                            <a class="menuBtn child" href="/seller/comingorders">2. Изделия в пути (до Астаны)</a>

                            <a class="menuBtn2 child" href="#">3. Изделия в офисе</a>
                            <a class="menuBtn child" style="padding-left: 25px; font-size: 13.4px;" href="/seller/readyforfitting">3.1. Неприглашенные на примерку</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/seller/infitting">3.2. Приглашенные на примерку</a>
                            <a class="menuBtn child" href="/seller/intailors">4. Изделия у портных</a>
                            <a class="menuBtn child" href="/seller/givencloth">5. Оставить отзыв клиента</a>

                            <a class="menuBtn header" href="#">Мои клиенты</a>
                            <a class="menuBtn child" href="/seller/clients">Изменить данные клиентов</a>
                            <a class="menuBtn child" href="/order">Поиск клиентов и изделии</a>
                            <a class="menuBtn child" href="/seller/happybd">Поздравить клиента с Д.Р.</a>

                            <a class="menuBtn header" href="#">Мои финансы</a>
                            <a class="menuBtn child" href="/seller/finance">Финансовые операции</a>
                            <a class="menuBtn child" href="/seller/cert">Сертификаты</a>
                            <a class="menuBtn child" href="/seller/profit">Мои продажи</a>
                            <a class="menuBtn child" href="/seller/tasks">Поручения</a>
                            <a class="menuBtn child" href="/seller/email">Запрос бухгалтеру</a>

                            <a class="menuBtn header" href="#">Мои документы</a>
                            <a class="menuBtn child" href="/seller/cycleslist">Список циклов</a>';

                    $redactorMenu = '
                             <button id="hideBtn" class="btn btn-default" onclick="hideMenu();"><span style="top: 2px;" class="glyphicon glyphicon-arrow-left"></span> Скрыть меню </button>

                             <a class="menuBtn header" href="#">Календарь</a>
                             <a class="menuBtn child" href="/redactor/myday">Мой день</a>

                             <a class="menuBtn header" href="#">Мои заказы</a>
                             <a class="menuBtn child" href="#">1. Обработать изделия</a>
                             <a class="menuBtn child" style="padding-left: 25px" href="/redactor/regcycles">1.1. Обычные циклы</a>
                             <a class="menuBtn child" style="padding-left: 25px" href="/redactor/urgentcycles">1.2. Срочные циклы</a>
                             <a class="menuBtn child" href="/redactor/failcodecheck">2. Не прошли сверку кодов</a>
                             <a class="menuBtn child" href="/redactor/readyforprod">3. Отправить на производство</a>
                             <a class="menuBtn child" href="/redactor/readyforshipping">4. Организовать доставку</a>

                            <a class="menuBtn header" href="#">Меню помощника</a>
                             <a class="menuBtn child" href="/redactor/copypaste">1. Copy & Paste (у помощника)</a>
                             <a class="menuBtn child" href="#">2. Сверка кодов изделия</a>
                              <a class="menuBtn child" style="padding-left: 25px" href="/redactor/inseller">2.1. У продавца</a>
                             <a class="menuBtn child" style="padding-left: 25px" href="/redactor/inredactor">2.2. Excel проверка(у помощника)</a>

                            <a class="menuBtn header" href="#">Ткани</a>
                            <a class="menuBtn child" href="#">1. В корзине</a>
                           <a class="menuBtn child" style="padding-left: 25px" href="/redactor/basketreg">1.1. Обычные</a>
                           <a class="menuBtn child" style="padding-left: 25px" href="/redactor/basketurgent">1.2. Срочные</a>
                           <a class="menuBtn child" href="#">2. В пути</a>
                           <a class="menuBtn child" style="padding-left: 25px" href="/redactor/comingreg">2.1. Обычные</a>
                           <a class="menuBtn child" style="padding-left: 25px" href="/redactor/comingurgent">2.2. Срочные</a>


                            <a class="menuBtn header" href="#">Мои запросы</a>
                             <a class="menuBtn child" href="/redactor/requests">Запрос бухгалтеру</a>
                            <a class="menuBtn child" href="/redactor/tasks">Поручения</a>

                             <a class="menuBtn header" href="#">Мои клиенты</a>
                             <a class="menuBtn child" href="/redactor/search">Поиск клиентов и изделии</a>

                             <a class="menuBtn header" href="#">Мои документы</a>
                             <a class="menuBtn child" href="/redactor/fabricurl">Список тканей</a>
                             <a class="menuBtn child" href="/redactor/cycleslist">Список циклов</a>';

                    $accountantMenu = '
                                        <a class="menuBtn child" href="/accountant">Финансовые операции</a>
                                        <a class="menuBtn child" href="/accountant/cert">Сертификаты</a>
                                        <a class="menuBtn child" href="/accountant/requests">Запросы сотрудников</a>
                                        <a class="menuBtn child" href="/accountant/tasks">Поручения сотрудникам</a>
                    ';

                    $directorMenu = '
                            <button id="hideBtn" class="btn btn-default" onclick="hideMenu();"><span style="top: 2px;" class="glyphicon glyphicon-arrow-left"></span> Скрыть меню </button>

                            <a class="menuBtn header" href="/director">Заказы</a>
                            <a class="menuBtn child" href="/director">Просмотреть все заказы</a>
                            <a class="menuBtn child" href="/director">Просмотреть заказы на исполнении</a>

                            <a class="menuBtn header" href="/director">Продавцы</a>
                            <a class="menuBtn child" href="/director">Просмотреть всех продавцов</a>
                            <a class="menuBtn child" href="/director">Составить статистику</a>
                            <a class="menuBtn child" href="/director">Написать письмо</a>

                            <a class="menuBtn header" href="/director">Редакторы</a>
                            <a class="menuBtn child" href="/director">Просмотреть всех редакторов</a>
                            <a class="menuBtn child" href="/director">Составить статистику</a>
                            <a class="menuBtn child" href="/director">Написать письмо</a>

                            <a class="menuBtn header" href="/director">Документы</a>
                            <a class="menuBtn child" href="/director">Изменить список тканей</a>
                            <a class="menuBtn child" href="/director">Изменить список циклов</a>
                            <a class="menuBtn child" href="/director">Изменить инструкцию пользывателя</a>';

                    $deliveryMenu = '
                            <button id="hideBtn" class="btn btn-default" onclick="hideMenu();"><span style="top: 2px;" class="glyphicon glyphicon-arrow-left"></span> Скрыть меню </button>


                            <a class="menuBtn header" href="#">Меню</a>
                            <a class="menuBtn child" href="/delivery">1. Copy & Paste (у помощника)</a>
                            <a class="menuBtn child" href="#">2. Сверка кодов изделия</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/delivery/inseller">2.1. У продавца</a>
                            <a class="menuBtn child" style="padding-left: 25px" href="/delivery/inredactor">3.2. Excel проверка(у помощника)</a>
                    ';

                    $adminMenu = '
                        <button id="hideBtn" class="btn btn-default" onclick="hideMenu();"><span style="top: 2px;" class="glyphicon glyphicon-arrow-left"></span> Скрыть меню </button>

                          <a class="menuBtn header" href="/admin">Пользыватели</a>
                          <a class="menuBtn child" href="/admin/add">Добавить нового пользывателя</a>

                          <a class="menuBtn header" href="/penalties">Штрафы</a>
                          <a class="menuBtn child" href="/penalties/add">Добавить новый штраф</a>

                          <a class="menuBtn header" href="/clients">Клиенты</a>
                          <a class="menuBtn child" href="/clients/add">Добавить нового клиента</a>

                          <a class="menuBtn header" href="/tailors">Портные</a>
                          <a class="menuBtn child" href="/tailors/add">Добавить нового портного</a>

                          <a class="menuBtn header" href="/admin">Заказы</a>
                          <a class="menuBtn child" href="/admin">Измененить статуса заказа</a>

                          <a class="menuBtn header" href="/cycles">Циклы</a>
                          <a class="menuBtn child" href="/cycles/add">Добавить новый цикл</a>

                          <a class="menuBtn header" href="/styles">Стили</a>
                          <a class="menuBtn child" href="/styles/add">Добавить новый стиль</a>

                          <a class="menuBtn header" href="/fabrics">Ткани</a>
                          <a class="menuBtn child" href="/fabrics/add">Добавить новую ткань</a>

                          <a class="menuBtn header" href="#">Поставщики/Связи</a>
                          <a class="menuBtn child" href="/suppliers">Поставщики</a>
                          <a class="menuBtn child" href="/suppliers/connections">Связи</a>

                          <a class="menuBtn header" href="/prices">Прайс-лист</a>
                          <a class="menuBtn child" href="/prices/add">Добавить новый прайс</a>

                          <a class="menuBtn header" href="/sms">СМС</a>

                          <a class="menuBtn header" href="/admin">Документы</a>
                          <a class="menuBtn child" href="/admin">Изменить инструкцию пользывателя</a>';

                    if ($this->identity() != null) {
                        switch ($this->identity()['access_type_id']) {
                            case 1: echo $sellerMenu; break;
                            case 2: echo $redactorMenu; break;
                            case 3: echo $accountantMenu; break;
                            case 4: echo $directorMenu; break;
                            case 5: echo $deliveryMenu; break;
                            case 6: echo $adminMenu; break;
                        }
                    }
                    ?>
                </div>

                <div class="right-section">
                    <button id="showBtn" style="display: none" class="btn btn-default" onclick="showMenu();"> Показать меню <span style="top: 3px;" class="glyphicon glyphicon-arrow-right"></span></button>
                    <?php echo $this->content; ?>
                </div>

            </div>

            <script>

                $(function() {

                    $(window).keydown(function (event) {
                        if (event.keyCode == 13) {
                            event.preventDefault();
                            return false;
                        }
                    });

                });


                containerWidth = $('.container').css('width');

                function hideMenu(){
                    $('#hideBtn').hide();
                    $('#showBtn').show();
                    $('.left-menu').hide();
                    $('.container').css('width','100%');
                    $('.right-section').css('width','100%');
                    $('.right-section').css('padding-left' , '0px');
                    $('.redactorNumColumns').width('75px');
                    $('.redactorClothColumn').width('80px');
                }
                function showMenu(){
                    $('#showBtn').hide();
                    $('#hideBtn').show();
                    $('.left-menu').show();
                    $('.container').css('width', containerWidth);
                    $('.right-section').css('width','75%');
                    $('.right-section').css('padding-left' , '40px');
                    $('.redactorNumColumns').width('auto');
                    $('.redactorClothColumn').width('auto');
                }
            </script>

        <?php
        }
        ?>

            <hr>
            <footer>
                <p style="float: right;">&copy; <?php echo date('Y') ?> Developed by Abu Andabekov, +77016538609. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>