<?php
//$title = 'Add new customer';
//$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('customer', array('action' => 'firststep')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
    <div class="header">
        Мои заказы
    </div>

    <a class="navBtn active">1 Шаг - Данные клиента</a>
    <a class="navBtn">2 Шаг - Замеры клиента</a>
    <a class="navBtn">3 Шаг - Заказ клиента</a>

<center>
    <div id="chooseContent">

        <b><div id="choosedContent"></div></b>
    <a class="navBtn chooseClient" >Выберите клиента</a>
    </div>
    <div>
        ИЛИ
    </div>
    <div>
        Зарегистрировать нового клиента
    </div>
</center>



    <div class="form-group">
        <?php $element = $form->get('firstname'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('lastname'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('middlename'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('birthday'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formDate($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('mobilephone'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('email'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('country'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('city'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('address'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('homephone'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('work'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('position'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('workaddress'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <?php $element = $form->get('workphone'); ?>
        <?php echo $this->formLabel($element); ?>
        <div class="col-xs-10">
            <?php echo $this->formText($element); ?>
        </div>
        <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

<?php

echo $this->form()->closeTag();
?>



<div id="myModal" class="modal large fade">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                <h4 class="modal-title">Выбор клиента</h4>

            </div>

            <div class="modal-body">

                <!--<p>Do you want to save changes you made to document before closing?</p>

                <p class="text-warning"><small>If you don't save, your changes will be lost.</small></p>-->


                <p>
                    <table id="customer-grid" class="table table-condensed table-hover table-striped" >
                        <thead>
                        <tr>
                            <th data-column-id="id" data-type="numeric" data-identifier="true">ID</th>
                            <th data-column-id="firstname">firstname</th>
                            <th data-column-id="lastname" data-order="desc">lastname</th>
                            <th data-column-id="middlename" data-order="desc">middlename</th>
                            <!--<th data-column-id="birthday" data-order="desc">birthday</th>-->
                            <th data-column-id="mobilephone" data-order="desc">mobilephone</th>
                            <th data-column-id="email" data-order="desc">email</th>
                            <th data-column-id="country" data-order="desc">country</th>
                            <th data-column-id="city" data-order="desc">city</th>
                            <th data-column-id="address" data-order="desc">address</th>
                            <!--<th data-column-id="homephone" data-order="desc">homephone</th>
                            <th data-column-id="work" data-order="desc">work</th>
                            <th data-column-id="position" data-order="desc">position</th>
                            <th data-column-id="workaddress" data-order="desc">workaddress</th>
                            <th data-column-id="workphone" data-order="desc">workphone</th>
                            <th data-column-id="link" data-formatter="link" data-sortable="false">Link</th>-->
                            <th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
                        </tr>
                        </thead>

                    </table>
                </p>


            </div>

            <div class="modal-footer">

                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                <button type="button" class="btn btn-primary">Save changes</button>

            </div>

        </div>

    </div>

</div>






<script type="text/javascript">

    $(document).ready(function(){
        init();

        $(".chooseClient").click(function(){

            $('#customer-grid').bootgrid('reload');
            $("#myModal").modal('show');

        });

        function init() {
            grid = $("#customer-grid").bootgrid({
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
                    };
                },
                url: "/restcustomer",
/*                selection: true,
                multiSelect: true,
                rowSelect: true,
                keepSelection: true,*/
                formatters: {
                    /*"link": function (column, row) {
                        return "<a href=\"customer/edit/"+row.id+"\">" + column.id + "</a>";
                    }*/
                    "commands": function(column, row)
                    {
                        return    "<button type=\"button\"  class=\"btn btn-xs btn-default command-choose-client\" data-row-id=\"" + row.id + "\">Выбрать</button>";
                    }
                }
            }).on("selected.rs.jquery.bootgrid", function(e, rows)
            {
                var rowIds = [];
                for (var i = 0; i < rows.length; i++)
                {
                    rowIds.push(rows[i].id);
                }
                alert("Select: " + rowIds.join(","));
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".command-choose-client").on("click", function(e)
                {
                    myId=$(this).data("row-id");
                    /*bootbox.setDefaults({
                        locale: "ru",
                        className: "my-modal"
                    });*/
                    /*$.post( "admin/delete/"+myId, { id: myId } ).done(function( data ) {
                        $('#customer-grid').bootgrid('reload');
                    });*/

                    $('input[name=id]').val(myId);

                    $.get( "/restcustomer/"+myId, { } ).done(function( data ) {

                        $('#choosedContent').html(" Выбранный клиент: " +data.lastname +" "+data.firstname+ " - "+ data.mobilephone);
                    });


                    $('#myModal').modal('hide');
                });
            });
        }
    });

</script>

