<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 01/05/2015
 * Time: 15:24
 */
?>

<div class="header">
    Ввести КОДы
</div>

<div class="subHeader">
    Данные, которые вводил продавец:
</div>

<?php
$form->setAttribute('action', $this->url('cycles', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('c_id'));

$monogramFlag = $form->get('product_id')->getValue()!='2' && $form->get('product_id')->getValue()!='4';
?>

<table class="myTable">

    <tr>
        <td>
            <?php $element = $form->get('cycle_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('product_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('textile_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('textile_class'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('typeof_measure'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('label_brand'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('style_number'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td></td>
        <td></td>

        <td>
            <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $form->get('seller_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td colspan="3"><?php echo $this->formTextArea($element); ?></td>
    </tr>

</table>

<?php
echo $this->form()->closeTag();
?>



<hr>
<div class="subHeader">
    Данные, для ввода редактором:
</div>

<?php
$sc_form->setAttribute('action', $this->url('redactor', array('action' => 'entercodes')));
$sc_form->setAttribute('class', 'form-horizontal');
$sc_form->prepare();

echo $this->form()->openTag($sc_form);
echo $this->formHidden($sc_form->get('id'));
?>


<table class="myTable">

    <tr>
        <td>
            <?php $element = $sc_form->get('system_code'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td>
            <?php $element = $sc_form->get('fabric_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td>
            <?php $element = $sc_form->get('description'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
    </tr>

    <tr>
        <td>
            <?php echo $this->formText($element); ?>
            <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
        </td>
        <td>
            <?php echo $this->formText($element); ?>
            <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
        </td>
        <td>
            <?php echo $this->formText($element); ?>
            <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
        </td>
    </tr>

</table>

    <button>Добавить строку</button>

<?php
echo $this->form()->closeTag();
?>