<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 01/05/2015
 * Time: 15:24
 */
?>

<div class="header">
    Ввести КОДы
</div>

<div style="float: left;">

    <div class="subHeader">
        Данные, которые вводил продавец:
    </div>

    <?php
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('c_id'));

        $monogramFlag = $form->get('product_id')->getValue()=='1' || $form->get('product_id')->getValue()=='5' || $form->get('product_id')->getValue()=='4';
    ?>

    <table class="myTable" width="600px">

        <tr>
            <td><b>ФИО клиента</b></td>
            <td colspan="3"> <input disabled class="form-control" value='<?php echo $clientName; ?>'/></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('cycle_id'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('first_monogram_location'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('product_id'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('first_monogram_font'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('textile_id'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formInput($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('first_monogram_font_color'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('fabric_class'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('first_monogram_caption'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formTextarea($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('typeof_measure'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('second_monogram_location'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('label_brand'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td>
                <?php echo $this->formSelect($element); ?>
                <span class="help-block" style="color:red"><?php echo $this->formElementErrors($element); ?></span>
            </td>

            <td>
                <?php if($monogramFlag) $element = $form->get('second_monogram_font'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('style_id'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('second_monogram_font_color'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td></td>
            <td></td>

            <td>
                <?php if($monogramFlag) $element = $form->get('second_monogram_caption'); ?>
                <?php if($monogramFlag) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($monogramFlag) echo $this->formTextarea($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $form->get('seller_comment'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td colspan="3"><?php echo $this->formTextArea($element); ?></td>
        </tr>
        <tr>
            <td><b>Заметки редактора</b></td>
            <td colspan="3"><textarea class="form-control" name="redactor_comment"><?=$redactor_comment;?></textarea></td>
        </tr>

    </table>

    <?php
        echo $this->form()->closeTag();
    ?>

</div>

<div style="float: left; width:710px;">

    <?php
        $sc_form->setAttribute('class', 'form-horizontal');
        $sc_form->prepare();
        echo $this->form()->openTag($sc_form);
    ?>

    <div class="subHeader">
        Системные коды:
    </div>

    <div id="testModel">
        <?php
            $systemCodeForm = $sc_form->get('systemcode');
            echo $this->formCollection($systemCodeForm);
        ?>
    </div>

    <?php
        echo $this->formHidden($sc_form->get('csrf'));
    ?>

    <button type="button" class="btn btn-default" onclick="addCode()">Добавить строку</button><br /><br />

    <table>
        <tr>
            <td>
                <span><b>Выберите статус кодов:</b></span>
            </td>
            <td>
                <select name="custom_status" class="form-control" style="width: 200px; display: inline; margin-right: 15px;">
                    <option value="0">New</option>
                    <option value="1">Some code</option>
                    <option value="5">Waiting response</option>
                    <option value="3">Ready</option>
                    <option value="4">Returned by Seller</option>
                    <option value="7">Returned by Assistant</option>
                    <option value="111">Аннулированный</option>
                </select>
            </td>
        </tr>

        <tr>
            <td>
                <span><b>Выберите статус ткани:</b></span>
            </td>
            <td>
                <select name="fabric_status" class="form-control" style="width: 200px; display: inline; margin-right: 15px;">
                    <option value="0">New</option>
                    <option value="6">Order fabric</option>
                    <option value="2">Waiting fabric</option>
                    <option value="3">Ready</option>
                </select>
            </td>
        </tr>
    </table>

    <br><br>
    <a class="btn btn-default cancel-btn" href="/redactor">Отменить</a>

    <textarea name="redactor_comment_2" style="display: none;"></textarea>

    <?php
        echo $this->formSubmit($sc_form->get('submit'));
        echo $this->form()->closeTag();
    ?>

</div>

<script>
    $(function() {

        hideMenu();

        $('textarea[name=seller_comment]').css('height','170px');
        $('textarea[name=redactor_comment]').css('height','100px');

        styleRows();
        var fieldsets = $('#testModel').find('fieldset');
        for(i=0; i<fieldsets.length; i++){
            if(i!=0 && i!=1) $(fieldsets[i]).find('span').remove();
        }

        if($('textarea[name=redactor_comment]').val()==''){
            $('textarea[name=redactor_comment]').val('Цикл:'+$('input[name=cycle_id]').val()+'\nВсе ОК');
            $('textarea[name=redactor_comment_2]').val('Цикл:'+$('input[name=cycle_id]').val()+'\nВсе ОК');
        } else {
            $('textarea[name=redactor_comment_2]').val($('textarea[name=redactor_comment]').val());
        }

        $('textarea[name=redactor_comment]').change(function() {
            $('textarea[name=redactor_comment_2]').val($(this).val());
        });


        $('select[name=custom_status').val(<?=$code_status?>);
        $('select[name=fabric_status').val(<?=$fabric_status?>);
    });

    function addCode(){
        var currentCount = $('#testModel').find('fieldset').length;
        var template = $('#testModel').find('span').last().data('template');
        template = template.replace(/__mycount__/g, currentCount);

        $('#testModel').find('fieldset').last().after(template);
        $('#testModel').find('fieldset').last().find('span').remove();
        styleRows();
        return false;
    }

    function deleteRowClick(row){
        row.parent().remove();
    }

    function styleRows(){
        $('#testModel').find('fieldset').find('label').css('margin-right', '5px');
    }
</script>