<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 19/06/2015
 * Time: 19:57
 */
?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="header">
    Изделия на Copy & Paste (помощник редактора)
</div>

<div class="col-md-9">
    <table id="ordercloth-grid" class="table table-condensed table-hover table-striped" data-row-select="true"
           data-keep-selection="true">
        <thead>
        <tr>
            <th data-header-css-class="redactorNumColumns2" data-type="numeric" data-column-id="cycle_id" data-order="desc">Цикл*</th>
            <th data-column-id="customer_full_name" >Клиент*</th>
            <th data-header-css-class="redactorNumColumns2" data-column-id="my_id">ID*</th>
            <th data-header-css-class="redactorNumColumns2" data-column-id="excel_order_id">HK_ID</th>
            <th data-header-css-class="redactorClothColumn" data-column-id="clother">Изделие*</th>
            <th data-column-id="fabric_class">Класс ткани</th>
            <th data-header-css-class="redactorNumColumns" data-type="numeric" data-column-id="textile_id">Ткань</th>
            <th data-type="code" data-column-id="code_status">Code status</th>
            <th data-type="fabric_status" data-column-id="fabric_status">Fabric status</th>
            <th data-column-id="seller_full_name">Помощник*</th>

            <th data-header-css-class="redactorColumnBtn" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
        </tr>
        </thead>
    </table>
</div>


<div id="sendToSellerDlg" style="display: none;">
    <input type="text" id="hiddenId" style="display: none;" />

    Подтверждаю, что обработал изделие: <br />
    <ul>
        <li>Преобразил изделие в системные коды</li>
        <li>Ткань в наличии на фабрике (заказал ткань и она доступна)</li>
        <li>Ввел коды в систему фабрики</li>
        <li>Конфликты в кодах устранил</li>
        <li>Сделал Presubmit. Ошибки не были найдены</li>
    </ul>
    Теперь отправляю продавцу на проверку.

    <table style="margin-top: 5px;">
        <tr>
            <td><b>Номер заказа (HK_ID):</b></td>
            <td>
                <input class="form-control" type="text" id="order_id" />
            </td>
        </tr>
        <tr>
            <td colspan="2"><span id="order_id_error" style="color: red; float: right;"></span></td>
        </tr>
    </table>

    <div style="text-align: center; margin-top: 15px;">
        <button onclick="closeDlg()" class="btn btn-default">Отмена</button>
        <button onclick="sendToSeller()" class="btn btn-primary">Отправить</button>
    </div>
</div>

<div id="returnToRedactorDlg" style="display: none;">

    <input type="text" id="hiddenId2" style="display: none;" />

    Напишите почему вы хотите вернуть редактору данное изделие:<br>

    <div style="text-align: center; margin-top: 15px;">
        <textarea id="assist_comment" name="assist_comment" style="height:110px; width: 400px;"></textarea><br>

        <span id="comment_error" style="color: red;"></span><br>

        <button onclick="closeDlg2()" class="btn btn-default">Отмена</button>
        <button onclick="returnToRedactor()" class="btn btn-primary">Отправить</button>
    </div>
</div>

<script>

    var test;
    var redactor_ids='';

    $(function () {

        hideMenu();

        function init() {
            var grid = $("#ordercloth-grid").bootgrid({
                rowCount: [50, 25, 10],
                ajax: true,
                post: function () {
                    /* To accumulate custom parameter with the request object */
                    return {
                        id: "b0df282a-0d67-40e5-8558-c9e93b7befed",
                        order_id: -1,
                        seller_name: '',
                        order_status: 16
                    };
                },
                url: "/restorderclothes",
                converters: {
                    code: {
                        from: function (value) { return value; },
                        to: function (value) {
                            if(value==null || value==0){
                                return 'New';
                            } else if(value==1){
                                return 'Some codes';
                            } else if(value==2){
                                return 'Waiting fabric';
                            } else if(value==3){
                                return 'Ready';
                            } else if(value==4){
                                return 'Returned by Seller';
                            }  else if(value==5){
                                return 'Waiting response';
                            } else if(value==6){
                                return 'Need to order fabric';
                            } else if(value==111){
                                return 'Аннулированный';
                            } else if(value==7){
                                return 'Returned by Assistant';
                            }
                        }
                    },
                    fabric_status: {
                        from: function (value) { return value; },
                        to: function (value) {
                            if(value==null || value==0){
                                return 'New';
                            } else if(value==2){
                                return 'Waiting fabric';
                            } else if(value==3){
                                return 'Ready';
                            } else if(value==6){
                                return 'Need to order fabric';
                            }
                        }
                    }
                },
                formatters: {
                    "commands": function(column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-primary checkCodes\" data-row-id=\"" + row.my_id + "\">Просмотреть <br>коды</button> <br />"+
//                            "<button type=\"button\" class=\"btn btn-xs btn-primary compareCodes\" data-row-id=\"" + row.my_id + "\">Сравнить коды</button> <br />"+
                            "<button type=\"button\" class=\"btn btn-xs btn-success presubmit\" data-row-id=\"" + row.my_id + "\">Отправить <br>на проверку <br>продавцу</button><br>"+
                            "<button type=\"button\" class=\"btn btn-xs btn-danger denyCloth\" data-row-id=\"" + row.my_id + "\">Вернуть <br>редактору</button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function()
            {
                /* Executes after data is loaded and rendered */
                grid.find(".checkCodes").on("click", function(e)
                {
                    if(redactor_ids=='') {
                        <?php
                            $js_array = json_encode($ids);
                            echo "redactor_ids = ". $js_array . ";\n";
                        ?>
                    }

                    if(redactor_ids.indexOf($(this).data("row-id"))==-1){
                        alert('Введите коды, прежде чем просмотреть их!')
                    } else{
                        window.open("watchcodes/"+$(this).data("row-id"), '_blank');
                    }
                }).end().find(".presubmit").on("click", function(e)
                {
                    openDlg($(this).data("row-id"));

                }).end().find(".denyCloth").on("click", function(e)
                {
                    openDlg2($(this).data("row-id"));
//                        $.post( "redactor/denycloth/"+myId, { id: myId } ).done(function( data ) {
//                            $('#ordercloth-grid').bootgrid('reload');
//                        });
                });
            });
        }
        init();
    });

    function openDlg(id){
        $('#sendToSellerDlg').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 550,
            height: 350
        });

        $('#hiddenId').val(id);
    }
    function closeDlg(){
        $('#sendToSellerDlg').dialog('close');
        $('#order_id_error').text('');
        $('#order_id').val('');
    }

    function openDlg2(id){
        $('#returnToRedactorDlg').dialog({
            modal: true,
            resizable: false,
            draggable: false,
            width: 565,
            height: 290
        });

        $('#hiddenId2').val(id);
    }
    function closeDlg2(){
        $('#returnToRedactorDlg').dialog('close');
        $('#comment_error').text('');
    }

    function sendToSeller(){
        if($('#order_id').val()==''){
            $('#order_id_error').text('Введите номер заказа');
        } else{
            $.post( "sendtoseller/"+$('#hiddenId').val(), { id: $('#hiddenId').val(), order_id: $('#order_id').val() } ).done(function( data ) {
                $('#ordercloth-grid').bootgrid('reload');
                closeDlg();
            });
        }
    }

    function returnToRedactor(){
        if($('#assist_comment').val()==''){
            $('#comment_error').text('Напишите причину');
        } else{
            $.post( "backtoredactor/"+$('#hiddenId2').val(), { id: $('#hiddenId2').val(), assist_comment: $('#assist_comment').val() } ).done(function( data ) {
                $('#ordercloth-grid').bootgrid('reload');
                closeDlg2();
            });
        }
    }

</script>