<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 10.04.2015
 * Time: 15:20
 */
?>
<div class="myContainer">

    <script type="text/javascript">
        $(function() {
            $('#welcomeText').text('Добро пожаловать, <?php echo $info->read()['surname']." ".$info->read()['name'] ?>!');
        });
    </script>

    <div class="left-menu">

        <a class="menuBtn header" href="/seller">Мои заказы</a>
        <a class="menuBtn child" href="/seller">Обработать изделия</a>
        <a class="menuBtn child" href="/seller">Сверка кодов изделия</a>
        <a class="menuBtn child" href="/seller">Отправить на производство</a>
        <a class="menuBtn child" href="/seller">Организовать доставку</a>
        <a class="menuBtn child" href="/seller">Изменить коды на изделия</a>

        <a class="menuBtn header" href="/seller">Мои клиенты</a>
        <a class="menuBtn child" href="/seller">Поиск клиентов и изделии</a>

        <a class="menuBtn header" href="/seller">Мои документы</a>
        <a class="menuBtn child" href="/seller">Список тканей</a>
        <a class="menuBtn child" href="/seller">Список циклов</a>
        <a class="menuBtn child" href="/seller">Инструкция пользывателя</a>

    </div>

    <div class="right-section">
        <div class="header">
            Мои заказы - Изделия в обработке
        </div>

    </div>

</div>