<?php
/**
 * Created by PhpStorm.
 * User: Abu Andabekov
 * Date: 01/05/2015
 * Time: 15:24
 */
?>

<div class="header">
    Просмотреть КОДы
</div>

<div class="subHeader">
    Данные, которые вводил редактор:
</div>

<?php
    $monogramFlag = $en_form->get('cloth_type')->getValue()!='2' && $en_form->get('cloth_type')->getValue()!='3';
    $en_form->setAttribute('class', 'form-horizontal');
    $en_form->prepare();
    echo $this->form()->openTag($en_form);
    echo $this->formHidden($en_form->get('order_cloth_id'));
?>

<table class="myTable makeDisabled">

    <tr>
        <td><b>ФИО клиента</b></td>
        <td colspan="3"> <input disabled class="form-control" value='<?php echo $clientName; ?>'/></td>
    </tr>

    <tr>
        <td>
            <?php $element = $en_form->get('cloth_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>

        <td>
            <?php $element = $en_form->get('fabric_id'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $en_form->get('measurement_type'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formText($element); ?></td>

        <td>
            <?php $element = $en_form->get('brand_label'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td><?php echo $this->formSelect($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_pos'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_color_font'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram1_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>

        <td>
            <?php if($monogramFlag) $element = $en_form->get('monogram2_text'); ?>
            <?php if($monogramFlag) echo $this->formLabel($element); ?>
        </td>
        <td><?php if($monogramFlag) echo $this->formText($element); ?></td>
    </tr>

    <tr>
        <td>
            <?php $element = $en_form->get('redactor_comment'); ?>
            <?php echo $this->formLabel($element); ?>
        </td>
        <td colspan="3"><?php echo $this->formTextArea($element); ?></td>
    </tr>
</table>

<?php
    echo $this->form()->closeTag();
?>
<hr>

<div class="subHeader">
    Замеры по <?php if($measurement_type==1) echo "фигуре"; else echo "изделию"; ?>:
</div>
<?php
if($measurement_type==1){
    $bm_form->setAttribute('class', 'form-horizontal');
    $bm_form->prepare();
    echo $this->form()->openTag($bm_form);
    ?>
    <table class="myTable makeDisabled" >
        <tr>
            <td>
                <?php $element = $bm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==1 || $cloth_type==5) $element = $bm_form->get('arm_position'); ?>
                <?php if($cloth_type==1 || $cloth_type==5) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==1 || $cloth_type==5) echo $this->formSelect($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('butt_position'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formSelect($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $bm_form->get('neck'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $bm_form->get('chest'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $bm_form->get('stomach'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=3) $element = $bm_form->get('seat'); ?>
                <?php if($cloth_type!=3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('thigh'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('knee_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('pant_bottom_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('u_rise'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('u_rise_auto'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('otseam_l_and_r'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $bm_form->get('nape_to_waist'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $bm_form->get('front_waist_length'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2 || $cloth_type==3) $element = $bm_form->get('back_waist_height'); ?>
                <?php if($cloth_type==2 || $cloth_type==3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2 || $cloth_type==3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2 || $cloth_type==3) $element = $bm_form->get('front_waist_height'); ?>
                <?php if($cloth_type==2 || $cloth_type==3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2 || $cloth_type==3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2 && $cloth_type!=3) $element = $bm_form->get('biceps'); ?>
                <?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2 && $cloth_type!=3) $element = $bm_form->get('back_shoulder'); ?>
                <?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2 && $cloth_type!=3) $element = $bm_form->get('right_sleeve'); ?>
                <?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2 && $cloth_type!=3) $element = $bm_form->get('left_sleeve'); ?>
                <?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2 && $cloth_type!=3) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=5 && $cloth_type!=2) $element = $bm_form->get('back_length'); ?>
                <?php if($cloth_type!=5 && $cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=5 && $cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==5) $element = $bm_form->get('overcoat_back_length'); ?>
                <?php if($cloth_type==5) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==5) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $bm_form->get('waist'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==4) $element = $bm_form->get('right_wrist'); ?>
                <?php if($cloth_type==4) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==4) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==4) $element = $bm_form->get('left_wrist'); ?>
                <?php if($cloth_type==4) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==4) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $bm_form->get('style'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formSelect($element); ?></td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
} else {
    ?>
    <?php
    $cm_form->setAttribute('class', 'form-horizontal');
    $cm_form->prepare();
    echo $this->form()->openTag($cm_form);
    ?>
    <table class="myTable makeDisabled" >
        <tr>
            <td>
                <?php $element = $cm_form->get('growth'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php $element = $cm_form->get('weight'); ?>
                <?php echo $this->formLabel($element); ?>
            </td>
            <td><?php echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('chest_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('stomach_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('jacket_seat_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('biceps_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('left_sleeve_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('right_sleeve_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('back_length_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('front_length_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type!=2) $element = $cm_form->get('shoulder_finished'); ?>
                <?php if($cloth_type!=2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type!=2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('waist_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('seat_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('thigh_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('outseam_l_and_r_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('knee_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('pant_bottom_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==2) $element = $cm_form->get('u_rise_finished'); ?>
                <?php if($cloth_type==2) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==2) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==4) $element = $cm_form->get('right_cuff'); ?>
                <?php if($cloth_type==4) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==4) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==4) $element = $cm_form->get('left_cuff'); ?>
                <?php if($cloth_type==4) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==4) echo $this->formText($element); ?></td>
        </tr>
        <tr>
            <td>
                <?php if($cloth_type==4) $element = $cm_form->get('shirt_neck'); ?>
                <?php if($cloth_type==4) echo $this->formLabel($element); ?>
            </td>
            <td><?php if($cloth_type==4) echo $this->formText($element); ?></td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag();
}
?>
<hr />

<div class="subHeader">
    Системные коды:
</div>
<div id="testModel">
<?php
    $sc_form->setAttribute('action', $this->url('redactor', array('action' => 'watchcodes', 'id' => $this->id)));
    $sc_form->setAttribute('class', 'form-horizontal');
    $sc_form->prepare();
    echo $this->form()->openTag($sc_form);
    $systemCodeForm = $sc_form->get('systemcode');
    echo $this->formCollection($systemCodeForm);
    echo $this->formHidden($sc_form->get('csrf'));
?>
    <button type="button" class="btn btn-default" onclick="addCode()">Добавить строку</button><br />

    <hr>

    <a class="btn btn-default cancel-btn" href="/redactor/copypaste">Вернутся</a>

<?php
    echo $this->formSubmit($sc_form->get('submit'));
    echo $this->form()->closeTag();
?>


</div>


<!--<input class="btn btn-success" type="submit" value="Сохранить"/>-->

<?php
//    echo $this->formSubmit($sc_form->get('submit'));
//    echo $this->form()->closeTag();
?>

<script>
    function sendForCheck(){
        myId=<?=$id;?>;
        bootbox.setDefaults({
            locale: "ru",
            className: "my-modal"
        });
        bootbox.confirm("" +
            "Подтверждаю, что обработал изделие: " +
            "<ul>" +
            "<li>Преобразил изделие в системные коды</li>" +
            "<li>Ткань в наличии на фабрике (заказал ткань и она доступна)</li>" +
            "<li>Ввел коды в систему фабрики</li>" +
            "<li>Конфликты в кодах устранил</li>" +
            "<li>Сделал Presubmit. Ошибки не были найдены</li>" +
            "</ul>"+
            "Теперь отправляю продавцу на проверку."
            , function(result) {
                if(result){
                    $.post( "../setstatus3/"+myId, { id: myId } ).done(function( data ) {
                        window.location='../success';
                    });
                }
            });
    }

    $(function() {

        $('textarea[name=redactor_comment]').css('height','100px');

        $('.makeDisabled input').attr('disabled', 'true');
        $('.makeDisabled select').attr('disabled', 'true');
        $('.makeDisabled textarea').attr('disabled', 'true');


//        $('input').attr('disabled', 'true');
//        $('select').attr('disabled', 'true');
//        $('textarea').attr('disabled', 'true');

//        $('button').remove();

        styleRows();

        var fieldsets = $('#testModel').find('fieldset');
        for(i=0; i<fieldsets.length; i++){
            if(i!=0 && i!=1) $(fieldsets[i]).find('span').remove();
        }
    });

    function styleRows(){
        $('#testModel').find('fieldset').find('label').css('margin-right', '20px');
    }

    function addCode(){
        var currentCount = $('#testModel').find('fieldset').length;
        var template = $('#testModel').find('span').last().data('template');
        template = template.replace(/__mycount__/g, currentCount);

        $('#testModel').find('fieldset').last().after(template);
        $('#testModel').find('fieldset').last().find('span').remove();
        styleRows();
        return false;
    }

    function deleteRowClick(row){
        row.parent().remove();
    }
</script>