<?php
/**
 * Created by PhpStorm.
 * User: abu.andabekov
 * Date: 05.04.2015
 * Time: 14:47
 *
 */

?>

<div id="container">
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>1));?>" class="mainButton">ПРОДАВЕЦ</a>
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>2));?>" class="mainButton">РЕДАКТОР</a>
    <br />
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>3));?>" class="mainButton">БУХГАЛТЕР</a>
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>4));?>" class="mainButton">ДИРЕКТОР</a>
    <br />
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>5));?>" class="mainButton">КУРЬЕР</a>
    <a href="<?php echo $this->url('pidzhak', array('action'=>'login', 'accessTypeId'=>6));?>" class="mainButton">АДМИНИСТРАТОР</a>
</div>
