CREATE TABLE `orderclothes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) DEFAULT NULL,
  `product_id`int(11) DEFAULT NULL COMMENT 'Наименование изделия',
  `cycle_id` int(11) DEFAULT NULL  COMMENT 'Номер цикла',
  `preferred_date` date DEFAULT NULL COMMENT 'Предпочтительная дата выдачи',
  `textile_id` int(11)  DEFAULT NULL COMMENT 'Номер ткани',
  `pricelistnum` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Номер прайс листа',
  `actual_amount` decimal(10,0) DEFAULT NULL COMMENT 'Фактическая сумма оплаты',
  `paytype_id` int(11) DEFAULT NULL COMMENT 'Тип оплаты',
  `typeof_measure`int(11) DEFAULT NULL COMMENT 'Вид замера',
  `label_brand` int(11)  DEFAULT NULL COMMENT 'Этикетка бранда',
  `style_id` int(11)  DEFAULT NULL COMMENT 'Номер стиля',
  `first_monogram_location` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1. Монограм (расположение)',
  `first_monogram_font` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1. Монограм (шрифт)',
  `first_monogram_font_color` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1. Монограм (цвет шрифта)',
  `first_monogram_caption` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1. Монограм (Надпись)',
  `second_monogram_location` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '2. Монограм (расположение)',
  `second_monogram_font` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '2. Монограм (шрифт)',
  `second_monogram_font_color` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '2. Монограм (цвет шрифта)',
  `second_monogram_caption` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '2. Монограм (Надпись)',
  `seller_comment` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Комментарии Продавца',
  PRIMARY KEY (`id`),
  KEY `orderclothers_order_id_ind` (`order_id`),
  KEY `orderclothers_product_id_ind` (`product_id`),
  KEY `orderclothers_cycle_id_ind` (`cycle_id`),
  KEY `orderclothers_textile_id_ind` (`textile_id`),
  KEY `orderclothers_paytype_id_ind` (`paytype_id`),
  KEY `orderclothers_style_id_ind` (`style_id`),
  CONSTRAINT `orderclothes_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `ordertable` (`id`),
  CONSTRAINT `orderclothes_product_id_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `clothers` (`id`),
  CONSTRAINT `orderclothes_paytype_id_ibfk_1` FOREIGN KEY (`paytype_id`) REFERENCES `paymenttypes` (`id`),
  CONSTRAINT `orderclothes_style_id_ibfk_1` FOREIGN KEY (`style_id`) REFERENCES `stylestable` (`id`),
  CONSTRAINT `orderclothes_cycle_id_ibfk_1` FOREIGN KEY (`cycle_id`) REFERENCES `cyclestable` (`id`),
  CONSTRAINT `orderclothes_textile_id_ibfk_1` FOREIGN KEY (`textile_id`) REFERENCES `fabricstable` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci