<table>
    <thead>
    <tr>
        <td></td>
        <th>Пиджак</th>
        <th>Брюки</th>
        <th>Пальто</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_right_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_left_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_shirt_neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_3')); ?></td>
    </tr>

    </tbody>
</table>


<script>
    $(document).ready(function(){
        $('input[name=c_growth_1]').bind("paste keyup", function() {
            $('input[name=c_growth_2]').val($(this).val()); $('input[name=c_growth_3]').val($(this).val());
        });
        $('input[name=c_growth_2]').bind("paste keyup", function() {
            $('input[name=c_growth_1]').val($(this).val()); $('input[name=c_growth_3]').val($(this).val());
        });
        $('input[name=c_growth_3]').bind("paste keyup", function() {
            $('input[name=c_growth_1]').val($(this).val()); $('input[name=c_growth_2]').val($(this).val());
        });

        $('input[name=c_weight_1]').bind("paste keyup", function() {
            $('input[name=c_weight_2]').val($(this).val()); $('input[name=c_weight_3]').val($(this).val());
        });
        $('input[name=c_weight_2]').bind("paste keyup", function() {
            $('input[name=c_weight_1]').val($(this).val()); $('input[name=c_weight_3]').val($(this).val());
        });
        $('input[name=c_weight_3]').bind("paste keyup", function() {
            $('input[name=c_weight_1]').val($(this).val()); $('input[name=c_weight_2]').val($(this).val());
        });
    });
</script>