<table>
    <thead>
    <tr>
        <td></td>
        <th>Пиджак</th>
        <th>Брюки</th>
        <th>Пальто</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_right_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_cuff_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_left_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_cuff_3')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_shirt_neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_2')); ?></td>
        <td><?php echo $this->formText($form->get('c_shirt_neck_3')); ?></td>
    </tr>

    </tbody>
</table>


<script>
    $(document).ready(function(){
        $('input[name=c_growth_1], input[name=c_growth_2], input[name=c_growth_3], input[name=c_weight_1], input[name=c_weight_2], input[name=c_weight_3]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=c_chest_finished_1], input[name=c_chest_finished_3], input[name=c_stomach_finished_1], input[name=c_stomach_finished_3], input[name=c_jacket_seat_finished_1], input[name=c_jacket_seat_finished_3], input[name=c_biceps_finished_1], input[name=c_biceps_finished_3], input[name=c_left_sleeve_finished_1], input[name=c_left_sleeve_finished_3], input[name=c_right_sleeve_finished_1], input[name=c_right_sleeve_finished_3]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=c_back_length_finished_1], input[name=c_back_length_finished_3], input[name=c_front_length_finished_1], input[name=c_front_length_finished_3], input[name=c_shoulder_finished_1], input[name=c_shoulder_finished_3], input[name=c_waist_finished_2], input[name=c_seat_finished_2]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=c_thigh_finished_2], input[name=c_outseam_l_and_r_finished_2], input[name=c_knee_finished_2], input[name=c_pant_bottom_finished_2], input[name=c_u_rise_finished_2], input[name=c_right_cuff_3], input[name=c_left_cuff_3], input[name=c_shirt_neck_3]').keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 || (e.keyCode == 65 && e.ctrlKey === true) || (e.keyCode >= 35 && e.keyCode <= 40)) { return; }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) { e.preventDefault(); }
        });

        $('input[name=c_growth_1]').bind("change paste keyup", function() {
            $('input[name=c_growth_2]').val($(this).val()); $('input[name=c_growth_3]').val($(this).val());
        });
        $('input[name=c_growth_2]').bind("change paste keyup", function() {
            $('input[name=c_growth_1]').val($(this).val()); $('input[name=c_growth_3]').val($(this).val());
        });
        $('input[name=c_growth_3]').bind("change paste keyup", function() {
            $('input[name=c_growth_1]').val($(this).val()); $('input[name=c_growth_2]').val($(this).val());
        });

        $('input[name=c_weight_1]').bind("change paste keyup", function() {
            $('input[name=c_weight_2]').val($(this).val()); $('input[name=c_weight_3]').val($(this).val());
        });
        $('input[name=c_weight_2]').bind("change paste keyup", function() {
            $('input[name=c_weight_1]').val($(this).val()); $('input[name=c_weight_3]').val($(this).val());
        });
        $('input[name=c_weight_3]').bind("change paste keyup", function() {
            $('input[name=c_weight_1]').val($(this).val()); $('input[name=c_weight_2]').val($(this).val());
        });
    });
</script>