<table>
    <thead>
    <tr>
        <td></td>
        <td>Пиджак</td>
        <td>Брюки</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_growth_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_weight_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_chest_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_stomach_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_jacket_seat_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_biceps_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_left_sleeve_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_right_sleeve_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_back_length_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_front_length_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_shoulder_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_waist_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_seat_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_thigh_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_outseam_l_and_r_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_knee_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_pant_bottom_finished_2')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_1')); ?></td>
        <td><?php echo $this->formText($form->get('c_u_rise_finished_2')); ?></td>
    </tr>
    </tbody>
</table>