<?php
$title = 'Add new measure';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('measure', array('action' => 'secondstep')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id_1'));
echo $this->formHidden($form->get('id_2'));
echo $this->formHidden($form->get('id_3'));
echo $this->formHidden($form->get('id_4'));
echo $this->formHidden($form->get('id_5'));

echo $this->formHidden($form->get('clother_id_1')->setValue(1));
echo $this->formHidden($form->get('clother_id_2')->setValue(2));
echo $this->formHidden($form->get('clother_id_3')->setValue(3));
echo $this->formHidden($form->get('clother_id_4')->setValue(4));
echo $this->formHidden($form->get('clother_id_5')->setValue(5));

echo $this->formHidden($form->get('customer_id_1'));
echo $this->formHidden($form->get('customer_id_2'));
echo $this->formHidden($form->get('customer_id_3'));
echo $this->formHidden($form->get('customer_id_4'));
echo $this->formHidden($form->get('customer_id_5'));
?>

    <div class="header">
        Замеры
    </div>

    <a class="navBtn">1 Шаг - Данные клиента</a>
    <a class="navBtn active">2 Шаг - Замеры клиента</a>
    <a class="navBtn">3 Шаг - Заказ клиента</a>

    <center>
        <div id="chooseContent">
            <?php
            echo 'Выбранный клиент: '.$customer->lastname." ".$customer->firstname." - ".$customer->mobilephone;
            ?>
        </div>
    </center>

<?= $this->render('bodyfields.phtml') ?>



<?php

echo $this->formHidden($form->get('c_id_1'));
echo $this->formHidden($form->get('c_id_2'));

echo $this->formHidden($form->get('c_clother_id_1')->setValue(1));
echo $this->formHidden($form->get('c_clother_id_2')->setValue(2));

echo $this->formHidden($form->get('c_customer_id_1'));
echo $this->formHidden($form->get('c_customer_id_2'));

?>

<?= $this->render('clothefields.phtml') ?>

<?php

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
